export const money=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n||0)

export function mapOpportunity(r:any){return {id:r.id,customerId:r.customer_id,title:r.title,stage:r.stage,value:+r.value||0,probability:r.probability||0,owner:r.owner_user_id||'',source:r.source||'',closeDate:r.close_date||'',notes:r.notes||'',createdAt:r.created_at}}
export function mapQuote(r:any){return {id:r.id,number:r.quote_number,customerId:r.customer_id,status:r.status,createdAt:r.created_at,sourceOpportunityId:r.opportunity_id||'',lines:(r.quote_lines||[]).sort((a:any,b:any)=>a.line_no-b.line_no).map((l:any)=>({id:l.id,category:l.category||'Labour / Other',sku:l.sku||'',code:l.sku||'',description:l.description,qty:+l.quantity||0,unit:+l.unit_price||0,discount:+l.discount_percent||0,vat:+l.vat_percent||0}))}}
export function mapSalesOrder(r:any){return {id:r.id,number:r.order_number,customerId:r.customer_id,status:r.status,deposit:+r.deposit||0,deliveryDate:r.requested_delivery||'',reference:r.customer_reference||'',notes:r.notes||'',sourceQuoteId:r.quote_id||'',sourceOpportunityId:r.opportunity_id||'',createdAt:r.created_at,lines:(r.sales_order_lines||[]).sort((a:any,b:any)=>a.line_no-b.line_no).map((l:any)=>({id:l.id,category:l.category||'Labour / Other',sku:l.sku||'',code:l.sku||'',description:l.description,qty:+l.quantity||0,unit:+l.unit_price||0,discount:+l.discount_percent||0,vat:+l.vat_percent||0}))}}
export function mapInvoice(r:any){return {id:r.id,number:r.invoice_number,customerId:r.customer_id,status:r.status,invoiceDate:r.invoice_date||'',dueDate:r.due_date||'',reference:r.customer_reference||'',notes:r.notes||'',sourceSalesOrderId:r.sales_order_id||'',sourceQuoteId:r.quote_id||'',sourceOpportunityId:r.opportunity_id||'',createdAt:r.created_at,lines:(r.invoice_lines||[]).sort((a:any,b:any)=>a.line_no-b.line_no).map((l:any)=>({id:l.id,category:l.category||'Labour / Other',sku:l.sku||'',code:l.sku||'',description:l.description,qty:+l.quantity||0,unit:+l.unit_price||0,discount:+l.discount_percent||0,vat:+l.vat_percent||0,make:l.machine_make||'',model:l.machine_model||'',serial:l.machine_serial||'',warrantyUntil:l.warranty_until||''}))}}
export const netLine=(l:any)=>(+l.qty||0)*(+l.unit||0)*(1-(+l.discount||0)/100)
export const grossTotal=(x:any)=>(x.lines||[]).reduce((s:number,l:any)=>s+netLine(l)*(1+(+l.vat||0)/100),0)
export const netTotal=(x:any)=>(x.lines||[]).reduce((s:number,l:any)=>s+netLine(l),0)
