import {createClient} from '../supabase/client';
import {getCloudContext} from './cloud';

const incomeCode=(category:string)=>({Machine:'3000',Parts:'3010',Service:'3020',Repair:'3030','Labour / Other':'3040'} as Record<string,string>)[category]||'3040';
const net=(l:any)=>(+l.quantity||0)*(+l.unit_price||0)*(1-(+l.discount_percent||0)/100);

async function accountMap(organizationId:string,codes:string[]){const supabase=createClient();const {data,error}=await supabase.from('chart_of_accounts').select('id,code').eq('organization_id',organizationId).in('code',codes);if(error)throw error;const map=new Map((data||[]).map((x:any)=>[x.code,x.id]));for(const c of codes)if(!map.get(c))throw new Error(`Ledger account ${c} is not configured.`);return map}
async function nextJournalNumber(organizationId:string){const supabase=createClient();const {count}=await supabase.from('journal_entries').select('*',{count:'exact',head:true}).eq('organization_id',organizationId);return `JE-${new Date().getFullYear()}-${String((count||0)+1).padStart(6,'0')}`}

export async function postInvoiceToLedger(invoiceId:string){const ctx=await getCloudContext(),supabase=createClient();const {data:existing}=await supabase.from('journal_entries').select('id').eq('organization_id',ctx.organizationId).eq('source_type','invoice').eq('source_id',invoiceId).limit(1);if(existing?.length)return existing[0].id;const {data:inv,error}=await supabase.from('invoices').select('*,invoice_lines(*)').eq('id',invoiceId).single();if(error)throw error;const lines=inv.invoice_lines||[],netBy=new Map<string,number>();let vat=0,total=0;for(const l of lines){const n=net(l),v=n*(+l.vat_percent||0)/100;netBy.set(incomeCode(l.category),(netBy.get(incomeCode(l.category))||0)+n);vat+=v;total+=n+v}const codes=['1100','2100',...Array.from(netBy.keys())],accounts=await accountMap(ctx.organizationId,codes);const {data:j,error:je}=await supabase.from('journal_entries').insert({organization_id:ctx.organizationId,depot_id:ctx.depotId,journal_number:await nextJournalNumber(ctx.organizationId),journal_date:inv.invoice_date,source_type:'invoice',source_id:invoiceId,reference:inv.invoice_number,description:`Sales invoice ${inv.invoice_number}`,status:'posted',created_by:ctx.userId,posted_at:new Date().toISOString()}).select('id').single();if(je)throw je;const entries:any[]=[{journal_entry_id:j.id,account_id:accounts.get('1100'),line_no:1,description:`Trade debtor ${inv.invoice_number}`,debit:+total.toFixed(2),credit:0,customer_id:inv.customer_id}];let i=2;for(const [code,amount] of netBy)entries.push({journal_entry_id:j.id,account_id:accounts.get(code),line_no:i++,description:`${inv.invoice_number} sales`,debit:0,credit:+amount.toFixed(2),customer_id:inv.customer_id});if(Math.abs(vat)>0.004)entries.push({journal_entry_id:j.id,account_id:accounts.get('2100'),line_no:i++,description:`Output VAT ${inv.invoice_number}`,debit:0,credit:+vat.toFixed(2),vat_amount:+vat.toFixed(2),vat_code:'T20',customer_id:inv.customer_id});const {error:le}=await supabase.from('journal_lines').insert(entries);if(le)throw le;return j.id}

export async function postPaymentToLedger(paymentId:string){const ctx=await getCloudContext(),supabase=createClient();const {data:existing}=await supabase.from('journal_entries').select('id').eq('organization_id',ctx.organizationId).eq('source_type','payment').eq('source_id',paymentId).limit(1);if(existing?.length)return existing[0].id;const {data:p,error}=await supabase.from('payments').select('*,invoices(invoice_number,customer_id)').eq('id',paymentId).single();if(error)throw error;const accounts=await accountMap(ctx.organizationId,['1000','1100']),invoice=(p as any).invoices;const {data:j,error:je}=await supabase.from('journal_entries').insert({organization_id:ctx.organizationId,depot_id:ctx.depotId,journal_number:await nextJournalNumber(ctx.organizationId),journal_date:p.payment_date,source_type:'payment',source_id:paymentId,reference:p.reference||invoice?.invoice_number||null,description:`Customer payment ${invoice?.invoice_number||''}`,status:'posted',created_by:ctx.userId,posted_at:new Date().toISOString()}).select('id').single();if(je)throw je;const amount=+p.amount||0;const {error:le}=await supabase.from('journal_lines').insert([{journal_entry_id:j.id,account_id:accounts.get('1000'),line_no:1,description:'Bank receipt',debit:amount,credit:0,customer_id:invoice?.customer_id||null},{journal_entry_id:j.id,account_id:accounts.get('1100'),line_no:2,description:`Receipt against ${invoice?.invoice_number||'invoice'}`,debit:0,credit:amount,customer_id:invoice?.customer_id||null}]);if(le)throw le;return j.id}
