"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Customer={id:string;name:string;company?:string;phone?:string;email?:string;postcode?:string;address?:string};
type Line={id:string;code:string;description:string;qty:number;unit:number;discount:number;vat:number};
const K="dealercore-v2";
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(n||0);
const uid=()=>crypto.randomUUID();
const blankLine=():Line=>({id:uid(),code:"",description:"",qty:1,unit:0,discount:0,vat:20});
const netLine=(l:Line)=>l.qty*l.unit*(1-l.discount/100);

export default function NewInvoice(){
 const [customers,setCustomers]=useState<Customer[]>([]); const [store,setStore]=useState<any>({});
 const [customerId,setCustomerId]=useState(""); const [customerQuery,setCustomerQuery]=useState(""); const [customerOpen,setCustomerOpen]=useState(false);
 const [invoiceDate,setInvoiceDate]=useState(new Date().toISOString().slice(0,10)); const [dueDate,setDueDate]=useState(new Date(Date.now()+14*86400000).toISOString().slice(0,10));
 const [reference,setReference]=useState(""); const [owner,setOwner]=useState(""); const [division,setDivision]=useState("Garden Machinery"); const [notes,setNotes]=useState("");
 const [lines,setLines]=useState<Line[]>([blankLine()]);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(K)||"{}");setStore(s);setCustomers(s.customers||[])}catch{}},[]);
 const selected=customers.find(c=>c.id===customerId);
 const matches=customers.filter(c=>`${c.company||""} ${c.name} ${c.postcode||""} ${c.email||""}`.toLowerCase().includes(customerQuery.toLowerCase())).slice(0,8);
 const totals=useMemo(()=>{const gross=lines.reduce((s,l)=>s+l.qty*l.unit,0);const discount=gross-lines.reduce((s,l)=>s+netLine(l),0);const net=gross-discount;const vat=lines.reduce((s,l)=>s+netLine(l)*l.vat/100,0);return{gross,discount,net,vat,total:net+vat}},[lines]);
 function choose(c:Customer){setCustomerId(c.id);setCustomerQuery(c.company||c.name);setCustomerOpen(false)}
 function update(id:string,patch:Partial<Line>){setLines(v=>v.map(x=>x.id===id?{...x,...patch}:x))}
 function save(){if(!customerId){alert("Choose a customer account first.");return}const invoices=store.invoices||[];const savedLines=lines.map(l=>({...l,sku:l.code,listPrice:l.unit,unit:l.unit*(1-l.discount/100)}));const invoice={id:uid(),number:`INV-${String(invoices.length+1).padStart(4,"0")}`,customerId,lines:savedLines,status:"Unpaid",notes:[reference?`Reference: ${reference}`:"",owner?`Owner: ${owner}`:"",division?`Division: ${division}`:"",notes].filter(Boolean).join("\n"),invoiceDate,dueDate,createdAt:new Date().toISOString()};const next={...store,invoices:[invoice,...invoices]};localStorage.setItem(K,JSON.stringify(next));window.location.href="/"}
 return <main className="doc-workspace commercial-doc"><header className="doc-workspace-head"><div><p>DEALERCORE / ACCOUNTS RECEIVABLE</p><h1>New Invoice</h1><span>Commercial invoice entry · Draft</span></div><div><Link href="/" className="secondary">Close</Link><button className="secondary">Save draft</button><button className="primary" onClick={save}>Approve & save</button></div></header>
 <div className="commercial-ribbon"><span>INVOICE</span><b>New document</b><small>Amounts in GBP · VAT registered transaction</small></div>
 <div className="doc-workspace-grid"><section className="doc-main">
 <div className="doc-section document-header-grid"><div><h2>Bill to</h2><label className="account-search"><span>Customer account</span><input value={customerQuery} onFocus={()=>setCustomerOpen(true)} onChange={e=>{setCustomerQuery(e.target.value);setCustomerId("");setCustomerOpen(true)}} placeholder="Type customer, company, postcode or email..." autoComplete="off"/>{customerOpen&&customerQuery&&<div className="account-results">{matches.map(c=><button type="button" key={c.id} onClick={()=>choose(c)}><b>{c.company||c.name}</b><span>{c.company?c.name:""} {c.postcode?`· ${c.postcode}`:""}</span><small>{c.email||c.phone||"Customer account"}</small></button>)}{!matches.length&&<div>No matching customer account</div>}</div>}</label>{selected&&<div className="selected-account"><b>{selected.company||selected.name}</b>{selected.company&&<span>{selected.name}</span>}<span>{selected.address||""} {selected.postcode||""}</span><small>{selected.email||""} {selected.phone||""}</small></div>}</div>
 <div><h2>Document details</h2><div className="doc-fields two"><label><span>Invoice date</span><input type="date" value={invoiceDate} onChange={e=>setInvoiceDate(e.target.value)}/></label><label><span>Due date</span><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label><span>Customer PO / reference</span><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="PO / job / customer ref"/></label><label><span>Salesperson / owner</span><input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="Account owner"/></label><label><span>Division</span><select value={division} onChange={e=>setDivision(e.target.value)}><option>Garden Machinery</option><option>Golf & Turf</option><option>Garden Care</option><option>Outdoor Living</option><option>Group</option></select></label><label><span>Currency</span><input value="GBP" readOnly/></label></div></div></div>
 <div className="doc-section line-section"><div className="doc-section-head"><div><h2>Invoice lines</h2><span className="section-hint">Products, parts, labour, installation and services</span></div><button className="secondary" onClick={()=>setLines(v=>[...v,blankLine()])}>+ Add line</button></div><div className="commercial-line-table"><div className="commercial-line-head"><span>Code / SKU</span><span>Description</span><span>Qty</span><span>Unit price</span><span>Disc %</span><span>VAT</span><span>Line total</span><span></span></div>{lines.map((l,index)=><div className="commercial-line" key={l.id}><input value={l.code} onChange={e=>update(l.id,{code:e.target.value})} placeholder="SKU / code"/><div className="description-cell"><input value={l.description} onChange={e=>update(l.id,{description:e.target.value})} placeholder="Enter product or service description"/><small>Line {index+1}</small></div><input type="number" min="0" step="1" value={l.qty} onChange={e=>update(l.id,{qty:+e.target.value})}/><div className="money-input"><span>£</span><input type="number" min="0" step="0.01" value={l.unit} onChange={e=>update(l.id,{unit:+e.target.value})}/></div><input type="number" min="0" max="100" step="0.1" value={l.discount} onChange={e=>update(l.id,{discount:+e.target.value})}/><select value={l.vat} onChange={e=>update(l.id,{vat:+e.target.value})}><option value="20">20%</option><option value="5">5%</option><option value="0">0%</option></select><strong>{money(netLine(l)*(1+l.vat/100))}</strong><button className="line-delete" onClick={()=>setLines(v=>v.length>1?v.filter(x=>x.id!==l.id):v)}>×</button></div>)}</div><button className="add-line-inline" onClick={()=>setLines(v=>[...v,blankLine()])}>+ Add another line</button></div>
 <div className="doc-section"><h2>Terms & notes</h2><textarea rows={6} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Payment terms, warranty notes, installation details, delivery information or other customer-facing notes..."/></div></section>
 <aside className="doc-summary commercial-summary"><div className="doc-summary-card status-card"><span>DOCUMENT STATUS</span><strong>Draft</strong><small>Not posted to receivables</small></div><div className="doc-summary-card"><span>INVOICE SUMMARY</span><div><small>Gross lines</small><b>{money(totals.gross)}</b></div>{totals.discount>0&&<div><small>Discounts</small><b>-{money(totals.discount)}</b></div>}<div><small>Net</small><b>{money(totals.net)}</b></div><div><small>VAT</small><b>{money(totals.vat)}</b></div><div className="grand"><small>Invoice total</small><strong>{money(totals.total)}</strong></div></div><div className="doc-summary-card"><span>ACCOUNT CONTROL</span><p><b>Account:</b> {selected?.company||selected?.name||"Not selected"}</p><p><b>Terms:</b> Due {dueDate}</p><p><b>Owner:</b> {owner||"Unassigned"}</p><p><b>Division:</b> {division}</p></div></aside></div>
 <footer className="doc-sticky"><Link href="/" className="secondary">Cancel / Close</Link><div><span><small>Net {money(totals.net)} · VAT {money(totals.vat)}</small><b>Total {money(totals.total)}</b></span><button className="secondary">Save draft</button><button className="primary" onClick={save}>Approve & save invoice</button></div></footer></main>
}