"use client";
import {useEffect,useMemo,useState} from 'react';
import DmsShell from '../../../DmsShell';
import FinanceNav from '../FinanceNav';
import {createClient} from '../../../../lib/supabase/client';
import {getCloudContext} from '../../../../lib/dealercore/cloud';
const money=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n||0);
const quarter=()=>{const d=new Date(),q=Math.floor(d.getMonth()/3);return[new Date(d.getFullYear(),q*3,1).toISOString().slice(0,10),new Date(d.getFullYear(),q*3+3,0).toISOString().slice(0,10)]};
export default function VatWorkspace(){const[start,setStart]=useState(quarter()[0]),[end,setEnd]=useState(quarter()[1]),[invoices,setInvoices]=useState<any[]>([]),[bills,setBills]=useState<any[]>([]);async function load(){try{await getCloudContext();const s=createClient();const[a,b]=await Promise.all([s.from('invoices').select('invoice_date,invoice_lines(*)'),s.from('supplier_bills').select('bill_date,net_total,vat_total,status')]);if(a.error)throw a.error;if(b.error)throw b.error;setInvoices(a.data||[]);setBills(b.data||[])}catch(e:any){alert(e.message)}}useEffect(()=>{load()},[]);const vat=useMemo(()=>{let b1=0,b4=0,b6=0,b7=0;for(const i of invoices.filter(x=>x.invoice_date>=start&&x.invoice_date<=end))for(const l of i.invoice_lines||[]){const net=(+l.quantity||0)*(+l.unit_price||0)*(1-(+l.discount_percent||0)/100);b6+=net;b1+=net*(+l.vat_percent||0)/100}for(const b of bills.filter(x=>x.bill_date>=start&&x.bill_date<=end&&x.status!=='Cancelled')){b7+=+b.net_total||0;b4+=+b.vat_total||0}return{b1,b2:0,b3:b1,b4,b5:b1-b4,b6,b7,b8:0,b9:0}},[invoices,bills,start,end]);return <DmsShell active="Finance" eyebrow="FINANCE / VAT CONTROL" title="VAT & Tax Control" subtitle="Digital VAT records, return preparation, review and period control"><FinanceNav active="VAT & Tax Control"/><div className="finance-period"><label>Period start<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Period end<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><section className="dms-panel"><div className="dms-panel-head"><div><h2>UK VAT Return working</h2><span>Calculated from cloud sales and purchase records</span></div></div><div className="vat-box-grid">{[[1,'VAT due on sales and outputs',vat.b1],[2,'VAT due on acquisitions',vat.b2],[3,'Total VAT due',vat.b3],[4,'VAT reclaimed on purchases',vat.b4],[5,vat.b5>=0?'Net VAT to pay':'Net VAT to reclaim',Math.abs(vat.b5)],[6,'Total sales excluding VAT',vat.b6],[7,'Total purchases excluding VAT',vat.b7],[8,'EU supplies',vat.b8],[9,'EU acquisitions',vat.b9]].map((x:any)=><div key={x[0]}><span>BOX {x[0]}</span><b>{x[1]}</b><strong>{money(x[2])}</strong></div>)}</div><div className="finance-warning">VAT working is calculated from DealerCore digital records. Direct HMRC MTD submission remains a separate integration stage.</div></section></DmsShell>}
