"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Tab = "dashboard"|"crm"|"quotes"|"invoices"|"workshop"|"diary"|"stock"|"suppliers";
type Line={id:string;description:string;qty:number;unit:number;vat:number};
type Customer={id:string;name:string;company:string;phone:string;email:string;address:string;postcode:string;notes:string};
type Equipment={id:string;customerId:string;make:string;model:string;serial:string;type:string;notes:string};
type Quote={id:string;number:string;customerId:string;lines:Line[];status:"Draft"|"Sent"|"Accepted"|"Rejected";notes:string;createdAt:string};
type Payment={id:string;invoiceId:string;amount:number;date:string;method:string};
type Invoice={id:string;number:string;customerId:string;lines:Line[];status:"Unpaid"|"Part Paid"|"Paid";notes:string;dueDate:string;createdAt:string};
type WorkshopJob={id:string;customerId:string;equipmentId:string;machine:string;serial:string;workRequired:string;status:"Booked"|"Awaiting approval"|"Awaiting parts"|"In progress"|"Finished"|"Collected";labourHours:number;labourRate:number;partsCost:number;partsSell:number;dueDate:string;notes:string};
type DiaryItem={id:string;customerId:string;title:string;type:string;date:string;time:string;done:boolean};
type StockItem={id:string;sku:string;description:string;qty:number;cost:number;sell:number;supplierId:string};
type Supplier={id:string;name:string;contact:string;phone:string;email:string;accountNo:string;notes:string};
type Store={customers:Customer[];equipment:Equipment[];quotes:Quote[];invoices:Invoice[];payments:Payment[];workshop:WorkshopJob[];diary:DiaryItem[];stock:StockItem[];suppliers:Supplier[];cashBuffer:number};

const STORAGE_KEY="dealercore-v2";
const oldKey="dealercore-v1";
const blank:Store={customers:[],equipment:[],quotes:[],invoices:[],payments:[],workshop:[],diary:[],stock:[],suppliers:[],cashBuffer:0};
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(n||0);
const today=()=>new Date().toISOString().slice(0,10);
const totals=(lines:Line[])=>{const net=lines.reduce((s,l)=>s+l.qty*l.unit,0);const vat=lines.reduce((s,l)=>s+l.qty*l.unit*(l.vat/100),0);return{net,vat,total:net+vat}};

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal wide" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h3>{title}</h3><button className="icon-btn" onClick={onClose}>×</button></div>{children}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function LinesEditor({lines,setLines}:{lines:Line[];setLines:(v:Line[])=>void}){const t=totals(lines);return <div className="line-editor"><div className="line-head"><span>Description</span><span>Qty</span><span>Unit ex VAT</span><span>VAT %</span><span/></div>{lines.map(l=><div className="line-row" key={l.id}><input value={l.description} onChange={e=>setLines(lines.map(x=>x.id===l.id?{...x,description:e.target.value}:x))}/><input type="number" min="0" step="1" value={l.qty} onChange={e=>setLines(lines.map(x=>x.id===l.id?{...x,qty:Number(e.target.value)}:x))}/><input type="number" min="0" step="0.01" value={l.unit} onChange={e=>setLines(lines.map(x=>x.id===l.id?{...x,unit:Number(e.target.value)}:x))}/><select value={l.vat} onChange={e=>setLines(lines.map(x=>x.id===l.id?{...x,vat:Number(e.target.value)}:x))}><option value={20}>20%</option><option value={5}>5%</option><option value={0}>0%</option></select><button type="button" onClick={()=>setLines(lines.filter(x=>x.id!==l.id))}>×</button></div>)}<button type="button" className="text-btn" onClick={()=>setLines([...lines,{id:uid(),description:"",qty:1,unit:0,vat:20}])}>+ Add line</button><div className="doc-totals"><span>Net {money(t.net)}</span><span>VAT {money(t.vat)}</span><strong>Total {money(t.total)}</strong></div></div>}

export default function DealerCoreApp(){
 const [tab,setTab]=useState<Tab>("dashboard");const [store,setStore]=useState<Store>(blank);const [ready,setReady]=useState(false);const [modal,setModal]=useState<string|null>(null);const [selectedCustomer,setSelectedCustomer]=useState<string|null>(null);const [editDoc,setEditDoc]=useState<{type:"quote"|"invoice";id:string}|null>(null);const [search,setSearch]=useState("");
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)setStore({...blank,...JSON.parse(raw)});else{const legacy=localStorage.getItem(oldKey);if(legacy){const l=JSON.parse(legacy);setStore({...blank,customers:l.customers||[],diary:l.diary||[],cashBuffer:l.cashBuffer||0,workshop:(l.workshop||[]).map((j:any)=>({...j,equipmentId:"",labourHours:0,labourRate:65,partsCost:0,partsSell:0,dueDate:j.bookedFor||today(),notes:""})),quotes:(l.quotes||[]).map((q:any)=>({...q,lines:[{id:uid(),description:q.description||"",qty:1,unit:q.net||0,vat:20}],notes:""})),invoices:(l.invoices||[]).map((i:any)=>({...i,lines:[{id:uid(),description:i.description||"",qty:1,unit:i.net||0,vat:20}],dueDate:today(),notes:""}))})}}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(STORAGE_KEY,JSON.stringify(store))},[store,ready]);
 const cname=(id:string)=>store.customers.find(c=>c.id===id)?.name||"Unknown customer";
 const paidFor=(invoiceId:string)=>store.payments.filter(p=>p.invoiceId===invoiceId).reduce((s,p)=>s+p.amount,0);
 const weeklyTurnover=useMemo(()=>{const n=new Date();const day=(n.getDay()+6)%7;const monday=new Date(n);monday.setHours(0,0,0,0);monday.setDate(n.getDate()-day);return store.payments.filter(p=>new Date(p.date)>=monday).reduce((s,p)=>s+p.amount,0)},[store.payments]);
 const unpaid=store.invoices.reduce((s,i)=>s+Math.max(0,totals(i.lines).total-paidFor(i.id)),0);const quotePipe=store.quotes.filter(q=>q.status==="Draft"||q.status==="Sent").reduce((s,q)=>s+totals(q.lines).total,0);const finished=store.workshop.filter(j=>j.status==="Finished").reduce((s,j)=>s+j.labourHours*j.labourRate+j.partsSell,0);
 const nav:[Tab,string,string][]=[["dashboard","Dashboard","▦"],["crm","CRM","◎"],["quotes","Quotations","◇"],["invoices","Invoices","£"],["workshop","Workshop","⚙"],["diary","Sales Diary","□"],["stock","Stock & Parts","▤"],["suppliers","Suppliers","⌂"]];
 const filtered=store.customers.filter(c=>`${c.name} ${c.company} ${c.phone} ${c.email} ${c.postcode}`.toLowerCase().includes(search.toLowerCase()));
 function saveCustomer(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const c:Customer={id:uid(),name:String(f.get("name")),company:String(f.get("company")),phone:String(f.get("phone")),email:String(f.get("email")),address:String(f.get("address")),postcode:String(f.get("postcode")),notes:String(f.get("notes"))};setStore(s=>({...s,customers:[c,...s.customers]}));setModal(null)}
 function printDoc(type:"quote"|"invoice",id:string){const d=type==="quote"?store.quotes.find(x=>x.id===id):store.invoices.find(x=>x.id===id);if(!d)return;const c=store.customers.find(x=>x.id===d.customerId);const t=totals(d.lines);const w=window.open("","_blank");if(!w)return;w.document.write(`<html><head><title>${d.number}</title><style>body{font-family:Arial;padding:40px;color:#172018}.top{display:flex;justify-content:space-between}.brand{color:#376f2b}table{width:100%;border-collapse:collapse;margin-top:30px}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}.tot{margin-left:auto;width:280px;margin-top:20px}.tot div{display:flex;justify-content:space-between;padding:5px}h1{margin:0}</style></head><body><div class="top"><div><h2 class="brand">DealerCore / Risborough Group</h2><p>Risborough Group</p></div><div><h1>${type==="quote"?"Quotation":"Invoice"}</h1><strong>${d.number}</strong></div></div><hr/><h3>${c?.name||""}</h3><p>${c?.company||""}<br>${c?.address||""}<br>${c?.postcode||""}<br>${c?.email||""}</p><table><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>VAT</th><th>Total</th></tr></thead><tbody>${d.lines.map(l=>`<tr><td>${l.description}</td><td>${l.qty}</td><td>${money(l.unit)}</td><td>${l.vat}%</td><td>${money(l.qty*l.unit*(1+l.vat/100))}</td></tr>`).join("")}</tbody></table><div class="tot"><div><span>Net</span><b>${money(t.net)}</b></div><div><span>VAT</span><b>${money(t.vat)}</b></div><div><span>Total</span><b>${money(t.total)}</b></div></div><p>${d.notes||""}</p></body></html>`);w.document.close();w.focus();w.print()}
 function convert(q:Quote){const inv:Invoice={id:uid(),number:`INV-${String(store.invoices.length+1).padStart(4,"0")}`,customerId:q.customerId,lines:q.lines,status:"Unpaid",notes:q.notes,dueDate:new Date(Date.now()+14*86400000).toISOString().slice(0,10),createdAt:new Date().toISOString()};setStore(s=>({...s,invoices:[inv,...s.invoices],quotes:s.quotes.map(x=>x.id===q.id?{...x,status:"Accepted"}:x)}));setTab("invoices")}
 function workshopProfit(j:WorkshopJob){return j.labourHours*j.labourRate+j.partsSell-j.partsCost}

 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">DC</div><div><strong>DealerCore</strong><span>The Core of Your Dealership</span></div></div><nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><b>{icon}</b>{label}</button>)}</nav><div className="sidebar-foot"><span>Risborough Group</span><small>Operational V1</small></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">RISBOROUGH GROUP</p><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div className="top-actions"><span className="live-dot">● Preview</span>{tab!=="dashboard"&&<button className="primary" onClick={()=>setModal(tab==="crm"?"customer":tab==="quotes"?"quote":tab==="invoices"?"invoice":tab==="workshop"?"workshop":tab==="diary"?"diary":tab==="stock"?"stock":"supplier")}>+ New</button>}</div></header>

 {tab==="dashboard"&&<section><div className="target-card"><div><p>WEEKLY CASH COLLECTED</p><h2>{money(weeklyTurnover)} <span>/ {money(2500)}</span></h2><small>{money(Math.max(0,2500-weeklyTurnover))} remaining to Target One</small></div><div className="progress"><div style={{width:`${Math.min(100,weeklyTurnover/2500*100)}%`}}/></div></div><div className="stats-grid"><div className="stat"><span>Quote pipeline</span><strong>{money(quotePipe)}</strong><small>Open opportunities</small></div><div className="stat"><span>Receivables</span><strong>{money(unpaid)}</strong><small>Outstanding invoice balances</small></div><div className="stat"><span>Finished workshop</span><strong>{money(finished)}</strong><small>Ready to invoice / collect</small></div><div className="stat"><span>Cash buffer</span><strong>{money(store.cashBuffer)}</strong><small>Target £10,000</small></div></div><div className="two-col"><div className="panel"><div className="panel-head"><h3>Today</h3><button onClick={()=>setTab("diary")}>Open diary</button></div>{store.diary.filter(d=>d.date===today()&&!d.done).map(d=><div className="action-row" key={d.id}><button className="tick" onClick={()=>setStore(s=>({...s,diary:s.diary.map(x=>x.id===d.id?{...x,done:true}:x)}))}>✓</button><div><strong>{d.title}</strong><span>{d.time} · {cname(d.customerId)}</span></div></div>)}{!store.diary.some(d=>d.date===today()&&!d.done)&&<div className="empty">No actions due today.</div>}</div><div className="panel"><div className="panel-head"><h3>Workshop attention</h3><button onClick={()=>setTab("workshop")}>View all</button></div>{store.workshop.filter(j=>j.status!=="Collected").slice(0,6).map(j=><div className="action-row" key={j.id}><span className="status-dot"/><div><strong>{j.machine}</strong><span>{cname(j.customerId)} · {j.status} · profit {money(workshopProfit(j))}</span></div></div>)}</div></div></section>}

 {tab==="crm"&&<section><div className="toolbar"><input placeholder="Search customers..." value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={()=>setModal("customer")}>+ Add customer</button></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Company</th><th>Phone</th><th>Email</th><th>Postcode</th><th/></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.company||"—"}</td><td>{c.phone||"—"}</td><td>{c.email||"—"}</td><td>{c.postcode||"—"}</td><td><button onClick={()=>setSelectedCustomer(c.id)}>Open account</button></td></tr>)}</tbody></table></div></section>}

 {tab==="quotes"&&<section><div className="toolbar"><p>{store.quotes.length} quotations</p><button className="primary" onClick={()=>setModal("quote")}>+ New quotation</button></div><div className="cards-list">{store.quotes.map(q=>{const t=totals(q.lines);return <div className="record" key={q.id}><div><span className="record-no">{q.number}</span><h3>{cname(q.customerId)}</h3><p>{q.lines.map(l=>l.description).filter(Boolean).join(" · ")||"No description"}</p></div><div className="record-right"><strong>{money(t.total)}</strong><select value={q.status} onChange={e=>setStore(s=>({...s,quotes:s.quotes.map(x=>x.id===q.id?{...x,status:e.target.value as Quote["status"]}:x)}))}><option>Draft</option><option>Sent</option><option>Accepted</option><option>Rejected</option></select><button onClick={()=>setEditDoc({type:"quote",id:q.id})}>Edit</button><button onClick={()=>printDoc("quote",q.id)}>Print/PDF</button>{q.status!=="Accepted"&&<button onClick={()=>convert(q)}>Convert</button>}</div></div>})}</div></section>}

 {tab==="invoices"&&<section><div className="toolbar"><p>{store.invoices.length} invoices · {money(unpaid)} outstanding</p><button className="primary" onClick={()=>setModal("invoice")}>+ New invoice</button></div><div className="cards-list">{store.invoices.map(i=>{const t=totals(i.lines);const paid=paidFor(i.id);const balance=Math.max(0,t.total-paid);return <div className="record" key={i.id}><div><span className="record-no">{i.number}</span><h3>{cname(i.customerId)}</h3><p>Due {i.dueDate} · paid {money(paid)} · balance {money(balance)}</p></div><div className="record-right"><strong>{money(t.total)}</strong><span className={`pill ${balance===0?"ok":""}`}>{balance===0?"Paid":paid>0?"Part Paid":"Unpaid"}</span><button onClick={()=>setEditDoc({type:"invoice",id:i.id})}>Edit</button><button onClick={()=>printDoc("invoice",i.id)}>Print/PDF</button><button onClick={()=>setModal(`payment:${i.id}`)}>Add payment</button></div></div>})}</div></section>}

 {tab==="workshop"&&<section><div className="toolbar"><p>{store.workshop.filter(j=>j.status!=="Collected").length} active jobs</p><button className="primary" onClick={()=>setModal("workshop")}>+ Book machine</button></div><div className="table-wrap"><table><thead><tr><th>Due</th><th>Customer</th><th>Machine</th><th>Work</th><th>Revenue</th><th>Profit</th><th>Status</th></tr></thead><tbody>{store.workshop.map(j=><tr key={j.id}><td>{j.dueDate}</td><td>{cname(j.customerId)}</td><td><strong>{j.machine}</strong><small className="block">{j.serial}</small></td><td>{j.workRequired}</td><td>{money(j.labourHours*j.labourRate+j.partsSell)}</td><td>{money(workshopProfit(j))}</td><td><select value={j.status} onChange={e=>setStore(s=>({...s,workshop:s.workshop.map(x=>x.id===j.id?{...x,status:e.target.value as WorkshopJob["status"]}:x)}))}><option>Booked</option><option>Awaiting approval</option><option>Awaiting parts</option><option>In progress</option><option>Finished</option><option>Collected</option></select></td></tr>)}</tbody></table></div></section>}

 {tab==="diary"&&<section><div className="calendar-grid">{Array.from({length:14}).map((_,n)=>{const d=new Date();d.setDate(d.getDate()+n);const key=d.toISOString().slice(0,10);const items=store.diary.filter(x=>x.date===key);return <div className="day-card" key={key}><div className="day-head"><strong>{d.toLocaleDateString("en-GB",{weekday:"short"})}</strong><span>{d.toLocaleDateString("en-GB",{day:"2-digit",month:"short"})}</span></div>{items.map(i=><button key={i.id} className={i.done?"done":""} onClick={()=>setStore(s=>({...s,diary:s.diary.map(x=>x.id===i.id?{...x,done:!x.done}:x)}))}><b>{i.time}</b><span>{i.title}</span><small>{cname(i.customerId)}</small></button>)}{!items.length&&<small className="muted">No activity</small>}</div>})}</div></section>}

 {tab==="stock"&&<section><div className="toolbar"><p>{store.stock.length} stock lines · {money(store.stock.reduce((s,x)=>s+x.qty*x.cost,0))} at cost</p><button className="primary" onClick={()=>setModal("stock")}>+ Add stock</button></div><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Description</th><th>Qty</th><th>Cost</th><th>Sell</th><th>Margin</th><th>Supplier</th></tr></thead><tbody>{store.stock.map(x=><tr key={x.id}><td>{x.sku}</td><td><strong>{x.description}</strong></td><td>{x.qty}</td><td>{money(x.cost)}</td><td>{money(x.sell)}</td><td>{money(x.sell-x.cost)}</td><td>{store.suppliers.find(s=>s.id===x.supplierId)?.name||"—"}</td></tr>)}</tbody></table></div></section>}

 {tab==="suppliers"&&<section><div className="toolbar"><p>{store.suppliers.length} suppliers</p><button className="primary" onClick={()=>setModal("supplier")}>+ Add supplier</button></div><div className="cards-list">{store.suppliers.map(s=><div className="record" key={s.id}><div><span className="record-no">{s.accountNo||"SUPPLIER"}</span><h3>{s.name}</h3><p>{s.contact} · {s.phone} · {s.email}</p></div><div className="record-right"><span>{s.notes}</span></div></div>)}</div></section>}
 </main>

 {selectedCustomer&&<CustomerAccount id={selectedCustomer} store={store} setStore={setStore} close={()=>setSelectedCustomer(null)} cname={cname}/>} 
 {editDoc&&<EditDocument edit={editDoc} store={store} setStore={setStore} close={()=>setEditDoc(null)}/>} 
 {modal&&<CreateModal kind={modal} store={store} setStore={setStore} close={()=>setModal(null)} saveCustomer={saveCustomer}/>} 
 </div>
}

function CustomerAccount({id,store,setStore,close,cname}:{id:string;store:Store;setStore:React.Dispatch<React.SetStateAction<Store>>;close:()=>void;cname:(id:string)=>string}){const c=store.customers.find(x=>x.id===id);if(!c)return null;const eq=store.equipment.filter(x=>x.customerId===id);const qs=store.quotes.filter(x=>x.customerId===id);const ins=store.invoices.filter(x=>x.customerId===id);const jobs=store.workshop.filter(x=>x.customerId===id);function addEquipment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const item:Equipment={id:uid(),customerId:id,make:String(f.get("make")),model:String(f.get("model")),serial:String(f.get("serial")),type:String(f.get("type")),notes:String(f.get("notes"))};setStore(s=>({...s,equipment:[item,...s.equipment]}));e.currentTarget.reset()}return <Modal title={`${c.name} — customer account`} onClose={close}><div className="account-grid"><div className="account-card"><h4>Contact</h4><p>{c.company}<br/>{c.phone}<br/>{c.email}<br/>{c.address}<br/>{c.postcode}</p><small>{c.notes}</small></div><div className="account-card"><h4>History</h4><p>{qs.length} quotes · {ins.length} invoices · {jobs.length} workshop jobs</p></div></div><h4>Equipment</h4><div className="mini-list">{eq.map(e=><div key={e.id}><strong>{e.make} {e.model}</strong><span>{e.type} · {e.serial}</span></div>)}</div><form className="form-grid compact" onSubmit={addEquipment}><div className="split"><Field label="Make"><input name="make" required/></Field><Field label="Model"><input name="model" required/></Field></div><div className="split"><Field label="Type"><input name="type" placeholder="Mower, robot, chainsaw..."/></Field><Field label="Serial"><input name="serial"/></Field></div><Field label="Notes"><textarea name="notes"/></Field><button className="primary">+ Add equipment</button></form><h4>Recent activity</h4><div className="mini-list">{qs.slice(0,3).map(q=><div key={q.id}><strong>{q.number} · {money(totals(q.lines).total)}</strong><span>Quotation · {q.status}</span></div>)}{ins.slice(0,3).map(i=><div key={i.id}><strong>{i.number} · {money(totals(i.lines).total)}</strong><span>Invoice</span></div>)}{jobs.slice(0,3).map(j=><div key={j.id}><strong>{j.machine}</strong><span>Workshop · {j.status}</span></div>)}</div></Modal>}

function EditDocument({edit,store,setStore,close}:{edit:{type:"quote"|"invoice";id:string};store:Store;setStore:React.Dispatch<React.SetStateAction<Store>>;close:()=>void}){const doc=edit.type==="quote"?store.quotes.find(x=>x.id===edit.id):store.invoices.find(x=>x.id===edit.id);const [lines,setLines]=useState<Line[]>(doc?.lines||[]);const [notes,setNotes]=useState(doc?.notes||"");if(!doc)return null;function save(){if(edit.type==="quote")setStore(s=>({...s,quotes:s.quotes.map(q=>q.id===edit.id?{...q,lines,notes}:q)}));else setStore(s=>({...s,invoices:s.invoices.map(i=>i.id===edit.id?{...i,lines,notes}:i)}));close()}return <Modal title={`Edit ${doc.number}`} onClose={close}><LinesEditor lines={lines} setLines={setLines}/><Field label="Notes"><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field><button className="primary full" onClick={save}>Save changes</button></Modal>}

function CreateModal({kind,store,setStore,close,saveCustomer}:{kind:string;store:Store;setStore:React.Dispatch<React.SetStateAction<Store>>;close:()=>void;saveCustomer:(e:FormEvent<HTMLFormElement>)=>void}){const [lines,setLines]=useState<Line[]>([{id:uid(),description:"",qty:1,unit:0,vat:20}]);if(kind==="customer")return <Modal title="New customer" onClose={close}><form className="form-grid" onSubmit={saveCustomer}><div className="split"><Field label="Name"><input name="name" required/></Field><Field label="Company"><input name="company"/></Field></div><div className="split"><Field label="Phone"><input name="phone"/></Field><Field label="Email"><input name="email" type="email"/></Field></div><Field label="Address"><textarea name="address"/></Field><div className="split"><Field label="Postcode"><input name="postcode"/></Field><Field label="Notes"><input name="notes"/></Field></div><button className="primary full">Create customer</button></form></Modal>;
 if(kind.startsWith("payment:")){const invoiceId=kind.split(":")[1];return <Modal title="Record payment" onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const p:Payment={id:uid(),invoiceId,amount:Number(f.get("amount")),date:String(f.get("date")),method:String(f.get("method"))};setStore(s=>({...s,payments:[p,...s.payments]}));close()}}><Field label="Amount"><input name="amount" type="number" step="0.01" required/></Field><Field label="Date"><input name="date" type="date" defaultValue={today()} required/></Field><Field label="Method"><select name="method"><option>Bank transfer</option><option>Card</option><option>Cash</option><option>Finance</option><option>Other</option></select></Field><button className="primary full">Record payment</button></form></Modal>}
 if(kind==="quote"||kind==="invoice")return <Modal title={kind==="quote"?"New quotation":"New invoice"} onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(kind==="quote"){const q:Quote={id:uid(),number:`Q-${String(store.quotes.length+1).padStart(4,"0")}`,customerId:String(f.get("customerId")),lines,status:"Draft",notes:String(f.get("notes")),createdAt:new Date().toISOString()};setStore(s=>({...s,quotes:[q,...s.quotes]}))}else{const i:Invoice={id:uid(),number:`INV-${String(store.invoices.length+1).padStart(4,"0")}`,customerId:String(f.get("customerId")),lines,status:"Unpaid",notes:String(f.get("notes")),dueDate:String(f.get("dueDate")),createdAt:new Date().toISOString()};setStore(s=>({...s,invoices:[i,...s.invoices]}))}close()}}><Field label="Customer"><select name="customerId" required><option value="">Select customer</option>{store.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><LinesEditor lines={lines} setLines={setLines}/>{kind==="invoice"&&<Field label="Due date"><input name="dueDate" type="date" defaultValue={new Date(Date.now()+14*86400000).toISOString().slice(0,10)}/></Field>}<Field label="Notes"><textarea name="notes"/></Field><button className="primary full">Create {kind}</button></form></Modal>;
 if(kind==="workshop")return <Modal title="Book workshop job" onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const j:WorkshopJob={id:uid(),customerId:String(f.get("customerId")),equipmentId:String(f.get("equipmentId")),machine:String(f.get("machine")),serial:String(f.get("serial")),workRequired:String(f.get("workRequired")),status:"Booked",labourHours:Number(f.get("labourHours")),labourRate:Number(f.get("labourRate")),partsCost:Number(f.get("partsCost")),partsSell:Number(f.get("partsSell")),dueDate:String(f.get("dueDate")),notes:String(f.get("notes"))};setStore(s=>({...s,workshop:[j,...s.workshop]}));close()}}><Field label="Customer"><select name="customerId" required><option value="">Select</option>{store.customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><div className="split"><Field label="Machine"><input name="machine" required/></Field><Field label="Serial"><input name="serial"/></Field></div><Field label="Work required"><textarea name="workRequired"/></Field><div className="split"><Field label="Labour hours"><input name="labourHours" type="number" step="0.25" defaultValue="1"/></Field><Field label="Labour rate"><input name="labourRate" type="number" step="0.01" defaultValue="65"/></Field></div><div className="split"><Field label="Parts cost"><input name="partsCost" type="number" step="0.01" defaultValue="0"/></Field><Field label="Parts sell"><input name="partsSell" type="number" step="0.01" defaultValue="0"/></Field></div><Field label="Due"><input name="dueDate" type="date" defaultValue={today()}/></Field><Field label="Technician notes"><textarea name="notes"/></Field><button className="primary full">Book job</button></form></Modal>;
 if(kind==="diary")return <Modal title="New diary item" onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const d:DiaryItem={id:uid(),customerId:String(f.get("customerId")),title:String(f.get("title")),type:String(f.get("type")),date:String(f.get("date")),time:String(f.get("time")),done:false};setStore(s=>({...s,diary:[d,...s.diary]}));close()}}><Field label="Customer"><select name="customerId"><option value="">No customer</option>{store.customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Title"><input name="title" required/></Field><div className="split"><Field label="Type"><select name="type"><option>Follow-up</option><option>Appointment</option><option>Demo</option><option>Installation</option><option>Delivery</option></select></Field><Field label="Date"><input name="date" type="date" defaultValue={today()}/></Field></div><Field label="Time"><input name="time" type="time"/></Field><button className="primary full">Add to diary</button></form></Modal>;
 if(kind==="stock")return <Modal title="Add stock item" onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const x:StockItem={id:uid(),sku:String(f.get("sku")),description:String(f.get("description")),qty:Number(f.get("qty")),cost:Number(f.get("cost")),sell:Number(f.get("sell")),supplierId:String(f.get("supplierId"))};setStore(s=>({...s,stock:[x,...s.stock]}));close()}}><div className="split"><Field label="SKU"><input name="sku"/></Field><Field label="Quantity"><input name="qty" type="number" defaultValue="1"/></Field></div><Field label="Description"><input name="description" required/></Field><div className="split"><Field label="Cost"><input name="cost" type="number" step="0.01"/></Field><Field label="Sell"><input name="sell" type="number" step="0.01"/></Field></div><Field label="Supplier"><select name="supplierId"><option value="">None</option>{store.suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><button className="primary full">Add stock</button></form></Modal>;
 return <Modal title="Add supplier" onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const s:Supplier={id:uid(),name:String(f.get("name")),contact:String(f.get("contact")),phone:String(f.get("phone")),email:String(f.get("email")),accountNo:String(f.get("accountNo")),notes:String(f.get("notes"))};setStore(x=>({...x,suppliers:[s,...x.suppliers]}));close()}}><Field label="Supplier name"><input name="name" required/></Field><div className="split"><Field label="Contact"><input name="contact"/></Field><Field label="Account no."><input name="accountNo"/></Field></div><div className="split"><Field label="Phone"><input name="phone"/></Field><Field label="Email"><input name="email" type="email"/></Field></div><Field label="Notes"><textarea name="notes"/></Field><button className="primary full">Add supplier</button></form></Modal>
}
