"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Tab = "dashboard" | "crm" | "quotes" | "invoices" | "workshop" | "diary";
type Customer = { id:string; name:string; company:string; phone:string; email:string; address:string; postcode:string; notes:string; createdAt:string };
type LineItem = { id:string; description:string; qty:number; unit:number; vatRate:number };
type Quote = { id:string; number:string; customerId:string; items:LineItem[]; notes:string; status:"Draft"|"Sent"|"Accepted"|"Rejected"; createdAt:string; validUntil:string };
type Invoice = { id:string; number:string; customerId:string; items:LineItem[]; notes:string; status:"Unpaid"|"Paid"; createdAt:string; dueDate:string; paidAt?:string };
type WorkshopJob = { id:string; number:string; customerId:string; machine:string; serial:string; workRequired:string; technicianNotes:string; status:"Booked"|"Awaiting approval"|"Awaiting parts"|"In progress"|"Finished"|"Collected"; value:number; bookedFor:string; dueDate:string };
type DiaryItem = { id:string; customerId:string; title:string; type:"Follow-up"|"Appointment"|"Demo"|"Installation"|"Delivery"; date:string; time:string; notes:string; done:boolean };
type Store = { customers:Customer[]; quotes:Quote[]; invoices:Invoice[]; workshop:WorkshopJob[]; diary:DiaryItem[]; cashBuffer:number };
type PrintDoc = { kind:"Quotation"|"Invoice"|"Workshop Job Card"; number:string; customer?:Customer; items?:LineItem[]; notes?:string; date?:string; due?:string; job?:WorkshopJob } | null;

const STORAGE_KEY="dealercore-v2";
const legacyKey="dealercore-v1";
const blankStore:Store={customers:[],quotes:[],invoices:[],workshop:[],diary:[],cashBuffer:0};
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const iso=()=>new Date().toISOString().slice(0,10);
const addDays=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(n||0);
const totals=(items:LineItem[])=>items.reduce((a,i)=>{const net=i.qty*i.unit;return {net:a.net+net,vat:a.vat+net*(i.vatRate/100)}},{net:0,vat:0});
const total=(items:LineItem[])=>{const t=totals(items);return t.net+t.vat};
const emptyItem=():LineItem=>({id:uid(),description:"",qty:1,unit:0,vatRate:20});

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="modal-backdrop" onMouseDown={onClose}><div className={`modal ${wide?"modal-wide":""}`} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h3>{title}</h3><button className="icon-btn" onClick={onClose}>×</button></div>{children}</div></div>}
function ItemsEditor({items,setItems}:{items:LineItem[];setItems:(v:LineItem[])=>void}){const t=totals(items);return <div className="items-editor"><div className="item-head"><span>Description</span><span>Qty</span><span>Unit ex VAT</span><span>VAT %</span><span></span></div>{items.map(i=><div className="item-row" key={i.id}><input value={i.description} onChange={e=>setItems(items.map(x=>x.id===i.id?{...x,description:e.target.value}:x))}/><input type="number" min="0" step="1" value={i.qty} onChange={e=>setItems(items.map(x=>x.id===i.id?{...x,qty:Number(e.target.value)}:x))}/><input type="number" min="0" step="0.01" value={i.unit} onChange={e=>setItems(items.map(x=>x.id===i.id?{...x,unit:Number(e.target.value)}:x))}/><select value={i.vatRate} onChange={e=>setItems(items.map(x=>x.id===i.id?{...x,vatRate:Number(e.target.value)}:x))}><option value={20}>20%</option><option value={5}>5%</option><option value={0}>0%</option></select><button type="button" onClick={()=>setItems(items.filter(x=>x.id!==i.id))}>×</button></div>)}<button type="button" className="secondary" onClick={()=>setItems([...items,emptyItem()])}>+ Add line</button><div className="doc-totals"><span>Net <b>{money(t.net)}</b></span><span>VAT <b>{money(t.vat)}</b></span><span>Total <b>{money(t.net+t.vat)}</b></span></div></div>}

export default function Home(){
 const [tab,setTab]=useState<Tab>("dashboard"); const [store,setStore]=useState<Store>(blankStore); const [loaded,setLoaded]=useState(false); const [modal,setModal]=useState<null|"customer"|"quote"|"invoice"|"workshop"|"diary">(null); const [search,setSearch]=useState(""); const [items,setItems]=useState<LineItem[]>([emptyItem()]); const [printDoc,setPrintDoc]=useState<PrintDoc>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(legacyKey);if(raw){const parsed=JSON.parse(raw);const customers=(parsed.customers||[]).map((c:any)=>({company:"",address:"",...c}));const quotes=(parsed.quotes||[]).map((q:any)=>q.items?q:{...q,items:[{id:uid(),description:q.description||"",qty:1,unit:Number(q.net||0),vatRate:20}],notes:"",validUntil:addDays(30)});const invoices=(parsed.invoices||[]).map((i:any)=>i.items?i:{...i,items:[{id:uid(),description:i.description||"",qty:1,unit:Number(i.net||0),vatRate:20}],notes:"",dueDate:addDays(14)});const workshop=(parsed.workshop||[]).map((j:any,idx:number)=>({number:`JOB-${String(idx+1).padStart(4,"0")}`,technicianNotes:"",dueDate:j.bookedFor||iso(),...j}));const diary=(parsed.diary||[]).map((d:any)=>({notes:"",...d}));setStore({...blankStore,...parsed,customers,quotes,invoices,workshop,diary});}}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEY,JSON.stringify(store))},[store,loaded]);
 const customer=(id:string)=>store.customers.find(c=>c.id===id); const customerName=(id:string)=>customer(id)?.name||"Unknown customer";
 const monday=useMemo(()=>{const n=new Date();const d=(n.getDay()+6)%7;const m=new Date(n);m.setHours(0,0,0,0);m.setDate(n.getDate()-d);return m},[]);
 const weeklyTurnover=store.invoices.filter(i=>i.status==="Paid"&&new Date(i.paidAt||i.createdAt)>=monday).reduce((s,i)=>s+total(i.items),0); const target=2500;
 const outstandingQuotes=store.quotes.filter(q=>q.status==="Draft"||q.status==="Sent").reduce((s,q)=>s+total(q.items),0); const unpaid=store.invoices.filter(i=>i.status==="Unpaid").reduce((s,i)=>s+total(i.items),0); const finishedValue=store.workshop.filter(j=>j.status==="Finished").reduce((s,j)=>s+j.value,0); const dueToday=store.diary.filter(d=>d.date===iso()&&!d.done);
 const nav:[Tab,string,string][]=[["dashboard","Dashboard","▦"],["crm","CRM","◎"],["quotes","Quotations","◇"],["invoices","Invoices","£"],["workshop","Workshop","⚙"],["diary","Sales Diary","□"]];
 const print=(doc:NonNullable<PrintDoc>)=>{setPrintDoc(doc);setTimeout(()=>window.print(),80)};
 function addCustomer(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const c:Customer={id:uid(),name:String(f.get("name")),company:String(f.get("company")),phone:String(f.get("phone")),email:String(f.get("email")),address:String(f.get("address")),postcode:String(f.get("postcode")),notes:String(f.get("notes")),createdAt:new Date().toISOString()};setStore(s=>({...s,customers:[c,...s.customers]}));setModal(null)}
 function addQuote(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const q:Quote={id:uid(),number:`Q-${String(store.quotes.length+1).padStart(4,"0")}`,customerId:String(f.get("customerId")),items,notes:String(f.get("notes")),status:"Draft",createdAt:new Date().toISOString(),validUntil:String(f.get("validUntil"))||addDays(30)};setStore(s=>({...s,quotes:[q,...s.quotes]}));setItems([emptyItem()]);setModal(null)}
 function addInvoice(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const i:Invoice={id:uid(),number:`INV-${String(store.invoices.length+1).padStart(4,"0")}`,customerId:String(f.get("customerId")),items,notes:String(f.get("notes")),status:"Unpaid",createdAt:new Date().toISOString(),dueDate:String(f.get("dueDate"))||addDays(14)};setStore(s=>({...s,invoices:[i,...s.invoices]}));setItems([emptyItem()]);setModal(null)}
 function convertQuote(q:Quote){const i:Invoice={id:uid(),number:`INV-${String(store.invoices.length+1).padStart(4,"0")}`,customerId:q.customerId,items:q.items,notes:q.notes,status:"Unpaid",createdAt:new Date().toISOString(),dueDate:addDays(14)};setStore(s=>({...s,invoices:[i,...s.invoices],quotes:s.quotes.map(x=>x.id===q.id?{...x,status:"Accepted"}:x)}));setTab("invoices")}
 function addWorkshop(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const j:WorkshopJob={id:uid(),number:`JOB-${String(store.workshop.length+1).padStart(4,"0")}`,customerId:String(f.get("customerId")),machine:String(f.get("machine")),serial:String(f.get("serial")),workRequired:String(f.get("workRequired")),technicianNotes:String(f.get("technicianNotes")),status:"Booked",value:Number(f.get("value")||0),bookedFor:String(f.get("bookedFor"))||iso(),dueDate:String(f.get("dueDate"))||iso()};setStore(s=>({...s,workshop:[j,...s.workshop]}));setModal(null)}
 function addDiary(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const d:DiaryItem={id:uid(),customerId:String(f.get("customerId")),title:String(f.get("title")),type:String(f.get("type")) as DiaryItem["type"],date:String(f.get("date")),time:String(f.get("time")),notes:String(f.get("notes")),done:false};setStore(s=>({...s,diary:[d,...s.diary]}));setModal(null)}
 const filtered=store.customers.filter(c=>`${c.name} ${c.company} ${c.phone} ${c.email} ${c.postcode}`.toLowerCase().includes(search.toLowerCase()));
 const diaryGroups=Array.from({length:14},(_,n)=>addDays(n)).map(date=>({date,items:store.diary.filter(d=>d.date===date).sort((a,b)=>a.time.localeCompare(b.time))}));
 const newForTab=()=>{setItems([emptyItem()]);setModal(tab==="crm"?"customer":tab==="quotes"?"quote":tab==="invoices"?"invoice":tab==="workshop"?"workshop":"diary")};
 return <><div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">DC</div><div><strong>DealerCore</strong><span>The Core of Your Dealership</span></div></div><nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><b>{icon}</b>{label}</button>)}</nav><div className="sidebar-foot"><span>Risborough Group</span><small>DealerCore V1</small></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">RISBOROUGH GROUP</p><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div className="top-actions"><span className="live-dot">● Preview</span><button className="primary" onClick={newForTab}>+ New</button></div></header>
 {tab==="dashboard"&&<section><div className="target-card"><div><p>WEEKLY PAID TURNOVER</p><h2>{money(weeklyTurnover)} <span>/ {money(target)}</span></h2><small>{money(Math.max(0,target-weeklyTurnover))} remaining to Target One</small></div><div className="progress"><div style={{width:`${Math.min(100,weeklyTurnover/target*100)}%`}}/></div></div><div className="stats-grid"><div className="stat"><span>Outstanding quotes</span><strong>{money(outstandingQuotes)}</strong><small>Live pipeline</small></div><div className="stat"><span>Unpaid invoices</span><strong>{money(unpaid)}</strong><small>Cash to collect</small></div><div className="stat"><span>Finished workshop</span><strong>{money(finishedValue)}</strong><small>Finished = cash waiting</small></div><div className="stat"><span>Cash buffer</span><strong>{money(store.cashBuffer)}</strong><small>Target £10,000</small></div></div><div className="two-col"><div className="panel"><div className="panel-head"><h3>Today&apos;s actions</h3><button onClick={()=>setModal("diary")}>+ Add</button></div>{dueToday.length?dueToday.map(d=><div className="action-row" key={d.id}><button className="tick" onClick={()=>setStore(s=>({...s,diary:s.diary.map(x=>x.id===d.id?{...x,done:true}:x)}))}>✓</button><div><strong>{d.title}</strong><span>{d.time} · {customerName(d.customerId)} · {d.type}</span></div></div>):<div className="empty">No actions due today.</div>}</div><div className="panel"><div className="panel-head"><h3>Workshop attention</h3><button onClick={()=>setTab("workshop")}>View all</button></div>{store.workshop.filter(j=>j.status!=="Collected").slice(0,6).map(j=><div className="action-row" key={j.id}><span className="status-dot"/><div><strong>{j.number} · {j.machine}</strong><span>{customerName(j.customerId)} · {j.status} · {money(j.value)}</span></div></div>)}{!store.workshop.length&&<div className="empty">No workshop jobs yet.</div>}</div></div></section>}
 {tab==="crm"&&<section><div className="toolbar"><input placeholder="Search customers..." value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={()=>setModal("customer")}>+ Add customer</button></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Company</th><th>Phone</th><th>Email</th><th>Address</th><th>Notes</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small className="block">{c.postcode}</small></td><td>{c.company||"—"}</td><td>{c.phone||"—"}</td><td>{c.email||"—"}</td><td>{c.address||"—"}</td><td>{c.notes||"—"}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No customers found.</div>}</div></section>}
 {tab==="quotes"&&<section><div className="toolbar"><p>{store.quotes.length} quotations · {money(outstandingQuotes)} pipeline</p><button className="primary" onClick={()=>{setItems([emptyItem()]);setModal("quote")}}>+ New quotation</button></div><div className="cards-list">{store.quotes.map(q=><div className="record" key={q.id}><div><span className="record-no">{q.number}</span><h3>{customerName(q.customerId)}</h3><p>{q.items.map(i=>i.description).filter(Boolean).join(" · ")||"No description"}</p></div><div className="record-right"><strong>{money(total(q.items))}</strong><select value={q.status} onChange={e=>setStore(s=>({...s,quotes:s.quotes.map(x=>x.id===q.id?{...x,status:e.target.value as Quote["status"]}:x)}))}><option>Draft</option><option>Sent</option><option>Accepted</option><option>Rejected</option></select><button onClick={()=>print({kind:"Quotation",number:q.number,customer:customer(q.customerId),items:q.items,notes:q.notes,date:q.createdAt.slice(0,10),due:q.validUntil})}>Print / PDF</button>{q.status!=="Accepted"&&<button onClick={()=>convertQuote(q)}>Convert to invoice</button>}</div></div>)}{!store.quotes.length&&<div className="empty">No quotations yet.</div>}</div></section>}
 {tab==="invoices"&&<section><div className="toolbar"><p>{store.invoices.length} invoices · {money(unpaid)} outstanding</p><button className="primary" onClick={()=>{setItems([emptyItem()]);setModal("invoice")}}>+ New invoice</button></div><div className="cards-list">{store.invoices.map(i=><div className="record" key={i.id}><div><span className="record-no">{i.number}</span><h3>{customerName(i.customerId)}</h3><p>Due {i.dueDate} · {i.items.map(x=>x.description).filter(Boolean).join(" · ")}</p></div><div className="record-right"><strong>{money(total(i.items))}</strong><button onClick={()=>print({kind:"Invoice",number:i.number,customer:customer(i.customerId),items:i.items,notes:i.notes,date:i.createdAt.slice(0,10),due:i.dueDate})}>Print / PDF</button><button className={i.status==="Paid"?"paid":""} onClick={()=>setStore(s=>({...s,invoices:s.invoices.map(x=>x.id===i.id?{...x,status:x.status==="Paid"?"Unpaid":"Paid",paidAt:x.status==="Paid"?undefined:new Date().toISOString()}:x)}))}>{i.status}</button></div></div>)}{!store.invoices.length&&<div className="empty">No invoices yet.</div>}</div></section>}
 {tab==="workshop"&&<section><div className="toolbar"><p>{store.workshop.filter(j=>j.status!=="Collected").length} active jobs · {money(finishedValue)} finished</p><button className="primary" onClick={()=>setModal("workshop")}>+ Book machine</button></div><div className="table-wrap"><table><thead><tr><th>Job</th><th>Customer</th><th>Machine</th><th>Work required</th><th>Due</th><th>Value</th><th>Status</th><th></th></tr></thead><tbody>{store.workshop.map(j=><tr key={j.id}><td><strong>{j.number}</strong><small className="block">Booked {j.bookedFor}</small></td><td>{customerName(j.customerId)}</td><td><strong>{j.machine}</strong><small className="block">{j.serial||"No serial"}</small></td><td>{j.workRequired}<small className="block">{j.technicianNotes}</small></td><td>{j.dueDate}</td><td>{money(j.value)}</td><td><select value={j.status} onChange={e=>setStore(s=>({...s,workshop:s.workshop.map(x=>x.id===j.id?{...x,status:e.target.value as WorkshopJob["status"]}:x)}))}>{["Booked","Awaiting approval","Awaiting parts","In progress","Finished","Collected"].map(x=><option key={x}>{x}</option>)}</select></td><td><button className="table-btn" onClick={()=>print({kind:"Workshop Job Card",number:j.number,customer:customer(j.customerId),job:j})}>Job card</button></td></tr>)}</tbody></table>{!store.workshop.length&&<div className="empty">No workshop jobs yet.</div>}</div></section>}
 {tab==="diary"&&<section><div className="toolbar"><p>Next 14 days · {store.diary.filter(d=>!d.done).length} open actions</p><button className="primary" onClick={()=>setModal("diary")}>+ Add diary item</button></div><div className="calendar-grid">{diaryGroups.map(g=><div className="day-card" key={g.date}><div className="day-head"><strong>{new Date(`${g.date}T12:00:00`).toLocaleDateString("en-GB",{weekday:"short"})}</strong><span>{new Date(`${g.date}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}</span></div>{g.items.length?g.items.map(d=><div className={`diary-event ${d.done?"done":""}`} key={d.id} onClick={()=>setStore(s=>({...s,diary:s.diary.map(x=>x.id===d.id?{...x,done:!x.done}:x)}))}><b>{d.time} {d.title}</b><span>{customerName(d.customerId)} · {d.type}</span>{d.notes&&<small>{d.notes}</small>}</div>):<small className="day-empty">No activity</small>}</div>)}</div></section>}
 </main></div>
 {modal==="customer"&&<Modal title="New customer" onClose={()=>setModal(null)}><form className="form-grid" onSubmit={addCustomer}><div className="split"><Field label="Customer name"><input name="name" required/></Field><Field label="Company"><input name="company"/></Field></div><div className="split"><Field label="Phone"><input name="phone"/></Field><Field label="Email"><input type="email" name="email"/></Field></div><Field label="Address"><textarea name="address" rows={2}/></Field><Field label="Postcode"><input name="postcode"/></Field><Field label="CRM notes"><textarea name="notes" rows={3}/></Field><button className="primary full">Create customer</button></form></Modal>}
 {modal==="quote"&&<Modal title="New quotation" wide onClose={()=>setModal(null)}><form className="form-grid" onSubmit={addQuote}><Field label="Customer"><select name="customerId" required><option value="">Select customer</option>{store.customers.map(c=><option value={c.id} key={c.id}>{c.name}{c.company?` — ${c.company}`:""}</option>)}</select></Field><ItemsEditor items={items} setItems={setItems}/><Field label="Valid until"><input type="date" name="validUntil" defaultValue={addDays(30)}/></Field><Field label="Terms / notes"><textarea name="notes" rows={3}/></Field><button className="primary full">Create quotation</button></form></Modal>}
 {modal==="invoice"&&<Modal title="New invoice" wide onClose={()=>setModal(null)}><form className="form-grid" onSubmit={addInvoice}><Field label="Customer"><select name="customerId" required><option value="">Select customer</option>{store.customers.map(c=><option value={c.id} key={c.id}>{c.name}{c.company?` — ${c.company}`:""}</option>)}</select></Field><ItemsEditor items={items} setItems={setItems}/><Field label="Due date"><input type="date" name="dueDate" defaultValue={addDays(14)}/></Field><Field label="Notes"><textarea name="notes" rows={3}/></Field><button className="primary full">Create invoice</button></form></Modal>}
 {modal==="workshop"&&<Modal title="Book workshop machine" onClose={()=>setModal(null)}><form className="form-grid" onSubmit={addWorkshop}><Field label="Customer"><select name="customerId" required><option value="">Select customer</option>{store.customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><div className="split"><Field label="Machine / model"><input name="machine" required/></Field><Field label="Serial number"><input name="serial"/></Field></div><Field label="Work required"><textarea name="workRequired" rows={3} required/></Field><Field label="Technician notes"><textarea name="technicianNotes" rows={2}/></Field><div className="split"><Field label="Booked for"><input type="date" name="bookedFor" defaultValue={iso()}/></Field><Field label="Target completion"><input type="date" name="dueDate" defaultValue={iso()}/></Field></div><Field label="Estimated / approved value inc VAT"><input type="number" step="0.01" name="value"/></Field><button className="primary full">Create job card</button></form></Modal>}
 {modal==="diary"&&<Modal title="New sales diary item" onClose={()=>setModal(null)}><form className="form-grid" onSubmit={addDiary}><Field label="Customer"><select name="customerId"><option value="">No customer</option>{store.customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Action"><input name="title" required/></Field><div className="split"><Field label="Type"><select name="type"><option>Follow-up</option><option>Appointment</option><option>Demo</option><option>Installation</option><option>Delivery</option></select></Field><Field label="Date"><input type="date" name="date" defaultValue={iso()} required/></Field></div><Field label="Time"><input type="time" name="time" defaultValue="09:00" required/></Field><Field label="Notes"><textarea name="notes" rows={3}/></Field><button className="primary full">Add to diary</button></form></Modal>}
 {printDoc&&<div className="print-sheet"><header><div><p>RISBOROUGH GROUP</p><h1>DealerCore</h1></div><div className="print-title"><strong>{printDoc.kind}</strong><span>{printDoc.number}</span></div></header><div className="print-meta"><div><b>Customer</b><span>{printDoc.customer?.name}</span><span>{printDoc.customer?.company}</span><span>{printDoc.customer?.address}</span><span>{printDoc.customer?.postcode}</span><span>{printDoc.customer?.email}</span><span>{printDoc.customer?.phone}</span></div>{printDoc.kind!=="Workshop Job Card"&&<div><b>Date</b><span>{printDoc.date}</span><b>{printDoc.kind==="Invoice"?"Due":"Valid until"}</b><span>{printDoc.due}</span></div>}</div>{printDoc.items&&<table><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>VAT</th><th>Total</th></tr></thead><tbody>{printDoc.items.map(i=><tr key={i.id}><td>{i.description}</td><td>{i.qty}</td><td>{money(i.unit)}</td><td>{i.vatRate}%</td><td>{money(i.qty*i.unit*(1+i.vatRate/100))}</td></tr>)}</tbody></table>}{printDoc.items&&<div className="print-totals">{(()=>{const t=totals(printDoc.items!);return <><span>Net <b>{money(t.net)}</b></span><span>VAT <b>{money(t.vat)}</b></span><span>Total <b>{money(t.net+t.vat)}</b></span></>})()}</div>}{printDoc.job&&<div className="job-print"><div><b>Machine</b><span>{printDoc.job.machine}</span></div><div><b>Serial</b><span>{printDoc.job.serial}</span></div><div><b>Booked</b><span>{printDoc.job.bookedFor}</span></div><div><b>Target completion</b><span>{printDoc.job.dueDate}</span></div><div className="full-width"><b>Work required</b><p>{printDoc.job.workRequired}</p></div><div className="full-width"><b>Technician notes</b><p>{printDoc.job.technicianNotes||""}</p><div className="write-lines"></div></div></div>}{printDoc.notes&&<div className="print-notes"><b>Notes</b><p>{printDoc.notes}</p></div>}<footer>Risborough Group · DealerCore</footer></div>}</>;
}
