import Link from 'next/link';
import type {CSSProperties} from 'react';

type Shortcut={label:string;href:string};
const config:Record<string,{title:string;shortcuts:Shortcut[]}>= {
  'Working Capital':{title:'Working Capital & Treasury',shortcuts:[{label:'Aged Debtors',href:'/dms/accounts/working-capital#aged-debtors'},{label:'Aged Creditors',href:'/dms/accounts/working-capital#aged-creditors'},{label:'Payment Runs',href:'/dms/accounts/working-capital#payment-runs'},{label:'13 Week Cash Flow',href:'/dms/accounts/working-capital#cash-flow'}]},
  'Purchase Ledger':{title:'Purchase Ledger',shortcuts:[{label:'Supplier Bills',href:'/dms/accounts/purchase-ledger'},{label:'Supplier Credits',href:'/dms/accounts/adjustments'},{label:'Payment Runs',href:'/dms/accounts/working-capital#payment-runs'},{label:'Aged Creditors',href:'/dms/accounts/working-capital#aged-creditors'}]},
  'Banking':{title:'Banking & Reconciliation',shortcuts:[{label:'Bank Accounts',href:'/dms/accounts/banking#bank-accounts'},{label:'Statement Import',href:'/dms/accounts/banking#import'},{label:'Reconciliation',href:'/dms/accounts/banking#reconciliation'},{label:'Unreconciled',href:'/dms/accounts/banking#unreconciled'}]},
  'VAT & Tax Control':{title:'VAT & Tax Control',shortcuts:[{label:'VAT Return',href:'/dms/accounts/vat'},{label:'VAT Detail',href:'/dms/accounts/vat#detail'},{label:'VAT Control',href:'/dms/accounts/vat#control'},{label:'Saved Returns',href:'/dms/accounts/vat#returns'}]},
  'Profitability':{title:'Dealership Profitability',shortcuts:[{label:'Revenue Streams',href:'/dms/accounts/profitability#streams'},{label:'Manufacturers',href:'/dms/accounts/profitability#manufacturers'},{label:'Margins',href:'/dms/accounts/profitability#margins'},{label:'Contribution',href:'/dms/accounts/profitability#contribution'}]},
  'Controls':{title:'Controls & Approvals',shortcuts:[{label:'Approval Rules',href:'/dms/accounts/controls#rules'},{label:'Approval Queue',href:'/dms/accounts/controls#queue'},{label:'Management Packs',href:'/dms/accounts/controls#packs'},{label:'Audit Controls',href:'/dms/accounts/controls#audit'}]},
  'Recurring':{title:'Recurring Accounting',shortcuts:[{label:'Recurring Journals',href:'/dms/accounts/recurring'},{label:'Active Templates',href:'/dms/accounts/recurring#templates'},{label:'Due Postings',href:'/dms/accounts/recurring#due'},{label:'History',href:'/dms/accounts/recurring#history'}]},
  'Adjustments':{title:'Credits & Adjustments',shortcuts:[{label:'Customer Credits',href:'/dms/accounts/adjustments#customer-credits'},{label:'Supplier Credits',href:'/dms/accounts/adjustments#supplier-credits'},{label:'Accruals',href:'/dms/accounts/adjustments#accruals'},{label:'Prepayments',href:'/dms/accounts/adjustments#prepayments'}]},
  'General Ledger':{title:'General Ledger',shortcuts:[{label:'Journal Register',href:'/dms/accounts/ledger'},{label:'Manual Journal',href:'/dms/accounts/ledger#manual-journal'},{label:'Recurring Journals',href:'/dms/accounts/recurring'},{label:'Financial Statements',href:'/dms/accounts/reports'}]},
  'Financial Statements':{title:'Financial Statements',shortcuts:[{label:'Profit & Loss',href:'/dms/accounts/reports#profit-loss'},{label:'Balance Sheet',href:'/dms/accounts/reports#balance-sheet'},{label:'Trial Balance',href:'/dms/accounts/reports#trial-balance'},{label:'General Ledger',href:'/dms/accounts/ledger'}]},
  'Stock Accounting':{title:'Stock Accounting',shortcuts:[{label:'Stock Valuation',href:'/dms/accounts/stock-accounting#valuation'},{label:'COGS',href:'/dms/accounts/stock-accounting#cogs'},{label:'Adjustments',href:'/dms/accounts/stock-accounting#adjustments'},{label:'Write Offs',href:'/dms/accounts/stock-accounting#write-offs'}]},
  'Fixed Assets':{title:'Fixed Assets',shortcuts:[{label:'Asset Register',href:'/dms/accounts/assets'},{label:'Add Asset',href:'/dms/accounts/assets#add-asset'},{label:'Depreciation',href:'/dms/accounts/assets#depreciation'},{label:'Disposals',href:'/dms/accounts/assets#disposals'}]},
  'Budgets & Forecasts':{title:'Budgets & Forecasts',shortcuts:[{label:'Budgets',href:'/dms/accounts/budgets'},{label:'Budget vs Actual',href:'/dms/accounts/budgets#variance'},{label:'Forecasts',href:'/dms/accounts/budgets#forecasts'},{label:'Cash Flow',href:'/dms/accounts/working-capital#cash-flow'}]},
  'Period Close':{title:'Period & Year End',shortcuts:[{label:'Close Checklist',href:'/dms/accounts/period-close'},{label:'Month End',href:'/dms/accounts/period-close#month-end'},{label:'Year End',href:'/dms/accounts/period-close#year-end'},{label:'Lock Dates',href:'/dms/accounts/period-close#lock-dates'}]}
};
const bar:CSSProperties={display:'grid',gridTemplateColumns:'220px minmax(190px,260px) 1fr',gap:14,alignItems:'center',padding:'11px 13px',margin:'0 0 14px',background:'#fff',border:'1px solid #d9e0da',borderRadius:6,boxShadow:'0 1px 3px rgba(20,35,26,.04)'};
const back:CSSProperties={display:'inline-flex',alignItems:'center',gap:6,textDecoration:'none',color:'#244d31',fontSize:11,fontWeight:800};
const moduleName:CSSProperties={display:'grid',gap:2,paddingLeft:13,borderLeft:'1px solid #e3e8e4'};
const label:CSSProperties={fontSize:8,fontWeight:800,letterSpacing:1,color:'#79857d'};
const title:CSSProperties={fontSize:13,color:'#213128'};
const shortcuts:CSSProperties={display:'flex',justifyContent:'flex-end',gap:6,flexWrap:'wrap'};
const shortcut:CSSProperties={textDecoration:'none',padding:'7px 10px',border:'1px solid #d5ddd7',borderRadius:4,background:'#f8faf8',color:'#33483a',fontSize:9,fontWeight:800,whiteSpace:'nowrap'};
export default function FinanceNav({active}:{active:string}){const section=config[active]||{title:active,shortcuts:[]};return <div style={bar}><Link href="/dms/accounts" style={back}>← Back to Finance Control Centre</Link><div style={moduleName}><span style={label}>FINANCE MODULE</span><strong style={title}>{section.title}</strong></div><div style={shortcuts}>{section.shortcuts.map(item=><Link key={item.label} href={item.href} style={shortcut}>{item.label}</Link>)}</div></div>}
