"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Customer={id:string;name:string;company?:string;phone?:string;email?:string;address?:string;postcode?:string;notes?:string};
type Equipment={id:string;customerId:string;make:string;model:string;serial:string;type:string;notes?:string};
type Quote={id:string;number:string;customerId:string;lines:{qty:number;unit:number;vat:number;description:string}[];status:string;createdAt:string};
type Invoice={id:string;number:string;customerId:string;lines:{qty:number;unit:number;vat:number;description:string}[];status:string;createdAt:string};
type Store={customers:Customer[];equipment:Equipment[];quotes:Quote[];invoices:Invoice[];payments:any[];workshop:any[];diary:any[];stock:any[];suppliers:any[];cashBuffer:number};
type Opportunity={id:string;customerId:string;title:string;stage:string;value:number;probability:number;owner:string;source:string;closeDate:string;notes:string};
const key="dealercore-v2", oppKey="dealercore-opportunities-v1";
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(n||0);
const total=(lines:any[]=[])=>lines.reduce((s,l)=>s+(Number(l.qty)||0)*(Number(l.unit)||0)*(1+(Number(l.vat)||0)/100),0);
const stages=["Lead","Qualified","Demo / Survey","Quoted","Negotiation","Won","Lost"];

export default function Enterprise(){
 const [store,setStore]=useState<Store>({customers:[],equipment:[],quotes:[],invoices:[],payments:[],workshop:[],diary:[],stock:[],suppliers:[],cashBuffer:0});
 const [opps,setOpps]=useState<Opportunity[]>([]); const [selected,setSelected]=useState<string>(""); const [showNew,setShowNew]=useState(false);
 useEffect(()=>{try{setStore(s=>({...s,...JSON.parse(localStorage.getItem(key)||"{}")}));setOpps(JSON.parse(localStorage.getItem(oppKey)||"[]"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem(oppKey,JSON.stringify(opps))},[opps]);
 const pipeline=useMemo(()=>opps.filter(o=>!['Won','Lost'].includes(o.stage)).reduce((s,o)=>s+o.value,0),[opps]);
 const weighted=useMemo(()=>opps.filter(o=>!['Won','Lost'].includes(o.stage)).reduce((s,o)=>s+o.value*o.probability/100,0),[opps]);
 const won=opps.filter(o=>o.stage==='Won').reduce((s,o)=>s+o.value,0); const customer=store.customers.find(c=>c.id===selected);
 const custEquip=store.equipment.filter(e=>e.customerId===selected), custQuotes=store.quotes.filter(q=>q.customerId===selected), custInv=store.invoices.filter(i=>i.customerId===selected), custOpps=opps.filter(o=>o.customerId===selected);
 function addOpp(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setOpps(v=>[{id:crypto.randomUUID(),customerId:String(f.get('customerId')),title:String(f.get('title')),stage:'Lead',value:Number(f.get('value')),probability:Number(f.get('probability')),owner:String(f.get('owner')),source:String(f.get('source')),closeDate:String(f.get('closeDate')),notes:String(f.get('notes'))},...v]);setShowNew(false)}
 return <main className="enterprise"><div className="enterprise-head"><div><p>DEALERCORE ENTERPRISE WORKSPACE</p><h1>CRM & Sales Command Centre</h1><span>Account intelligence, asset history and opportunity management.</span></div><div><Link href="/" className="secondary">← Operations</Link><button className="primary" onClick={()=>setShowNew(true)}>+ Opportunity</button></div></div>
 <div className="enterprise-kpis"><div><span>Open pipeline</span><strong>{money(pipeline)}</strong><small>{opps.filter(o=>!['Won','Lost'].includes(o.stage)).length} active opportunities</small></div><div><span>Weighted forecast</span><strong>{money(weighted)}</strong><small>Probability adjusted</small></div><div><span>Won business</span><strong>{money(won)}</strong><small>Current local dataset</small></div><div><span>Customer assets</span><strong>{store.equipment.length}</strong><small>Machines under management</small></div></div>
 <section className="enterprise-panel"><div className="enterprise-panel-head"><div><h2>Sales pipeline</h2><span>Move opportunities through the full commercial lifecycle.</span></div><button className="primary" onClick={()=>setShowNew(true)}>+ New opportunity</button></div><div className="pipeline-board">{stages.map(stage=><div className="pipeline-col" key={stage}><header><b>{stage}</b><span>{opps.filter(o=>o.stage===stage).length}</span></header>{opps.filter(o=>o.stage===stage).map(o=><article key={o.id}><small>{store.customers.find(c=>c.id===o.customerId)?.company||store.customers.find(c=>c.id===o.customerId)?.name||'Unassigned'}</small><h3>{o.title}</h3><strong>{money(o.value)}</strong><p>{o.probability}% · {o.owner||'Unassigned'} · {o.closeDate||'No close date'}</p><select value={o.stage} onChange={e=>setOpps(v=>v.map(x=>x.id===o.id?{...x,stage:e.target.value}:x))}>{stages.map(s=><option key={s}>{s}</option>)}</select></article>)}</div>)}</div></section>
 <div className="enterprise-grid"><section className="enterprise-panel"><div className="enterprise-panel-head"><div><h2>Customer accounts</h2><span>360° commercial and machine view.</span></div></div><div className="account-list">{store.customers.map(c=><button className={selected===c.id?'selected':''} key={c.id} onClick={()=>setSelected(c.id)}><div><b>{c.company||c.name}</b><span>{c.company?c.name:''}</span></div><small>{store.equipment.filter(e=>e.customerId===c.id).length} assets · {opps.filter(o=>o.customerId===c.id&&!['Won','Lost'].includes(o.stage)).length} opportunities</small></button>)}{!store.customers.length&&<p className="empty">Add customers in CRM first.</p>}</div></section>
 <section className="enterprise-panel account-detail">{customer?<><div className="account-title"><div><small>ACCOUNT</small><h2>{customer.company||customer.name}</h2><span>{customer.name} · {customer.phone||'No phone'} · {customer.email||'No email'}</span></div><span className="account-status">ACTIVE</span></div><div className="account-tabs"><div><span>Open opportunities</span><strong>{money(custOpps.filter(o=>!['Won','Lost'].includes(o.stage)).reduce((s,o)=>s+o.value,0))}</strong></div><div><span>Quoted</span><strong>{money(custQuotes.reduce((s,q)=>s+total(q.lines),0))}</strong></div><div><span>Invoiced</span><strong>{money(custInv.reduce((s,i)=>s+total(i.lines),0))}</strong></div><div><span>Assets</span><strong>{custEquip.length}</strong></div></div><h3>Machine / asset register</h3><div className="asset-list">{custEquip.map(e=><div key={e.id}><b>{e.make} {e.model}</b><span>{e.type} · S/N {e.serial||'—'}</span><small>{e.notes||'No asset notes'}</small></div>)}{!custEquip.length&&<p className="empty">No machines registered to this account.</p>}</div><h3>Commercial activity</h3><div className="activity-list">{custOpps.map(o=><p key={o.id}><b>{o.stage}</b> {o.title} <span>{money(o.value)}</span></p>)}{custQuotes.map(q=><p key={q.id}><b>QUOTE</b> {q.number} <span>{money(total(q.lines))}</span></p>)}{custInv.map(i=><p key={i.id}><b>INVOICE</b> {i.number} <span>{money(total(i.lines))}</span></p>)}</div></>:<div className="empty large">Select a customer account to open its 360° view.</div>}</section></div>
 {showNew&&<div className="modal-backdrop"><form className="modal form-grid" onSubmit={addOpp}><div className="modal-head"><h3>New sales opportunity</h3><button type="button" className="icon-btn" onClick={()=>setShowNew(false)}>×</button></div><label className="field"><span>Customer account</span><select name="customerId" required><option value="">Select customer</option>{store.customers.map(c=><option value={c.id} key={c.id}>{c.company||c.name}</option>)}</select></label><label className="field"><span>Opportunity</span><input name="title" required placeholder="e.g. Golf club robotic mower fleet"/></label><div className="split"><label className="field"><span>Value ex VAT</span><input name="value" type="number" min="0" step="0.01" required/></label><label className="field"><span>Probability %</span><input name="probability" type="number" min="0" max="100" defaultValue="25"/></label></div><div className="split"><label className="field"><span>Owner / salesperson</span><input name="owner" placeholder="Jonathan"/></label><label className="field"><span>Lead source</span><select name="source"><option>Existing customer</option><option>Website</option><option>Referral</option><option>Telephone</option><option>Showroom</option><option>Outbound</option><option>Manufacturer lead</option></select></label></div><label className="field"><span>Expected close date</span><input name="closeDate" type="date"/></label><label className="field"><span>Internal notes</span><textarea name="notes" rows={3}/></label><button className="primary full">Create opportunity</button></form></div>}
 </main>
}