"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const KEY="dealercore-business-settings-v1";

type Settings={legalName:string;tradingName:string;companyNumber:string;vatNumber:string;address1:string;address2:string;town:string;county:string;postcode:string;phone:string;email:string;website:string;bankName:string;sortCode:string;accountNumber:string;accountName:string;invoiceTerms:string;footerText:string;logoData:string;documentAccent:string};
const blank:Settings={legalName:"",tradingName:"",companyNumber:"",vatNumber:"",address1:"",address2:"",town:"",county:"",postcode:"",phone:"",email:"",website:"",bankName:"",sortCode:"",accountNumber:"",accountName:"",invoiceTerms:"Payment due within 14 days unless otherwise agreed.",footerText:"Thank you for your business.",logoData:"",documentAccent:"#173f1f"};

export default function BusinessSettings(){
 const [s,setS]=useState<Settings>(blank); const [saved,setSaved]=useState(false);
 useEffect(()=>{try{setS({...blank,...JSON.parse(localStorage.getItem(KEY)||"{}")})}catch{}},[]);
 function save(){localStorage.setItem(KEY,JSON.stringify(s));setSaved(true);setTimeout(()=>setSaved(false),1800)}
 function logo(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setS(v=>({...v,logoData:String(r.result)}));r.readAsDataURL(f)}
 const set=(k:keyof Settings,v:string)=>setS(x=>({...x,[k]:v}));
 return <main className="settings-shell"><header className="settings-head"><div><p>DEALERCORE / SYSTEM ADMINISTRATION</p><h1>Business Settings & Document Branding</h1><span>Legal entity, dealership identity, banking and document presentation.</span></div><div><Link href="/dms" className="secondary">Close</Link><button className="primary" onClick={save}>{saved?'Saved ✓':'Save settings'}</button></div></header>
 <div className="settings-layout"><aside className="settings-side"><b>Organisation</b><span>Company identity</span><span>Contact details</span><span>Tax & registration</span><b>Documents</b><span>Branding & logo</span><span>Bank details</span><span>Invoice terms</span><b>Scope</b><span>Default company profile</span><span>Multi-depot ready</span></aside>
 <section className="settings-main"><div className="settings-card"><h2>Company identity</h2><div className="settings-grid two"><label><span>Legal company name</span><input value={s.legalName} onChange={e=>set('legalName',e.target.value)} placeholder="Risborough Group Ltd"/></label><label><span>Trading name</span><input value={s.tradingName} onChange={e=>set('tradingName',e.target.value)} placeholder="Risborough Garden Machinery"/></label><label><span>Company number</span><input value={s.companyNumber} onChange={e=>set('companyNumber',e.target.value)}/></label><label><span>VAT number</span><input value={s.vatNumber} onChange={e=>set('vatNumber',e.target.value)}/></label></div></div>
 <div className="settings-card"><h2>Registered / trading address</h2><div className="settings-grid two"><label><span>Address line 1</span><input value={s.address1} onChange={e=>set('address1',e.target.value)}/></label><label><span>Address line 2</span><input value={s.address2} onChange={e=>set('address2',e.target.value)}/></label><label><span>Town / city</span><input value={s.town} onChange={e=>set('town',e.target.value)}/></label><label><span>County</span><input value={s.county} onChange={e=>set('county',e.target.value)}/></label><label><span>Postcode</span><input value={s.postcode} onChange={e=>set('postcode',e.target.value)}/></label></div></div>
 <div className="settings-card"><h2>Contact details</h2><div className="settings-grid two"><label><span>Telephone</span><input value={s.phone} onChange={e=>set('phone',e.target.value)}/></label><label><span>Email</span><input value={s.email} onChange={e=>set('email',e.target.value)}/></label><label><span>Website</span><input value={s.website} onChange={e=>set('website',e.target.value)}/></label></div></div>
 <div className="settings-card"><h2>Document branding</h2><div className="branding-grid"><div><label className="upload-box"><span>Dealership logo</span><input type="file" accept="image/*" onChange={logo}/><small>PNG, JPG or SVG-style image file supported in preview.</small></label>{s.logoData&&<div className="logo-preview"><img src={s.logoData} alt="Business logo preview"/><button onClick={()=>set('logoData','')}>Remove</button></div>}</div><div className="settings-grid one"><label><span>Document accent colour</span><input type="color" value={s.documentAccent} onChange={e=>set('documentAccent',e.target.value)}/></label><label><span>Invoice footer text</span><textarea rows={4} value={s.footerText} onChange={e=>set('footerText',e.target.value)}/></label></div></div></div>
 <div className="settings-card"><h2>Bank details</h2><div className="settings-grid two"><label><span>Bank name</span><input value={s.bankName} onChange={e=>set('bankName',e.target.value)}/></label><label><span>Account name</span><input value={s.accountName} onChange={e=>set('accountName',e.target.value)}/></label><label><span>Sort code</span><input value={s.sortCode} onChange={e=>set('sortCode',e.target.value)}/></label><label><span>Account number</span><input value={s.accountNumber} onChange={e=>set('accountNumber',e.target.value)}/></label></div></div>
 <div className="settings-card"><h2>Invoice terms</h2><textarea className="settings-textarea" rows={6} value={s.invoiceTerms} onChange={e=>set('invoiceTerms',e.target.value)}/></div>
 </section></div></main>
}