"use client";
import {useEffect,useState} from "react";
import DmsShell from "../../DmsShell";
import {getCloudContext} from "../../../lib/dealercore/cloud";
import {clearLegacyOperationalData,findLegacyOperationalKeys} from "../../../lib/dealercore/localData";

const KEY="dealercore-business-settings-v1";
type Settings={legalName:string;tradingName:string;companyNumber:string;vatNumber:string;address1:string;address2:string;town:string;county:string;postcode:string;phone:string;email:string;website:string;bankName:string;sortCode:string;accountNumber:string;accountName:string;invoiceTerms:string;footerText:string;logoData:string;documentAccent:string};
const blank:Settings={legalName:"",tradingName:"",companyNumber:"",vatNumber:"",address1:"",address2:"",town:"",county:"",postcode:"",phone:"",email:"",website:"",bankName:"",sortCode:"",accountNumber:"",accountName:"",invoiceTerms:"Payment due within 14 days unless otherwise agreed.",footerText:"Thank you for your business.",logoData:"",documentAccent:"#3f7650"};

export default function BusinessSettings(){
 const[s,setS]=useState<Settings>(blank),[saved,setSaved]=useState(false),[cloud,setCloud]=useState<'checking'|'connected'|'error'>('checking'),[cloudDetail,setCloudDetail]=useState('Checking Supabase connection…'),[legacyKeys,setLegacyKeys]=useState<string[]>([]),[armed,setArmed]=useState(false),[cleared,setCleared]=useState<string[]>([]);
 useEffect(()=>{try{setS({...blank,...JSON.parse(localStorage.getItem(KEY)||"{}")})}catch{}setLegacyKeys(findLegacyOperationalKeys());(async()=>{try{const ctx=await getCloudContext();setCloud('connected');setCloudDetail(`Cloud connected · ${ctx.role} · organisation ${ctx.organizationId.slice(0,8)}…`)}catch(e:any){setCloud('error');setCloudDetail(e.message||'Cloud connection unavailable')}})()},[]);
 const set=(k:keyof Settings,v:string)=>setS(x=>({...x,[k]:v}));
 function save(){localStorage.setItem(KEY,JSON.stringify(s));setSaved(true);setTimeout(()=>setSaved(false),1800)}
 function logo(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setS(v=>({...v,logoData:String(r.result)}));r.readAsDataURL(f)}
 function clearLegacy(){if(!armed){setArmed(true);return}const removed=clearLegacyOperationalData();setCleared(removed);setLegacyKeys(findLegacyOperationalKeys());setArmed(false)}
 return <DmsShell active="Settings" eyebrow="SYSTEM ADMINISTRATION" title="Business Settings & Document Branding" subtitle="Legal entity, dealership identity, banking and data management" actions={<button className="dms-primary" onClick={save}>{saved?'Saved ✓':'Save settings'}</button>}>
  <div className="settings-dms-grid">
   <section className="dms-panel dms-form-panel"><h2>Company identity</h2><div className="dms-form-two"><label><span>Legal company name</span><input value={s.legalName} onChange={e=>set('legalName',e.target.value)} placeholder="Risborough Group Ltd"/></label><label><span>Trading name</span><input value={s.tradingName} onChange={e=>set('tradingName',e.target.value)} placeholder="Risborough Garden Machinery"/></label><label><span>Company number</span><input value={s.companyNumber} onChange={e=>set('companyNumber',e.target.value)}/></label><label><span>VAT number</span><input value={s.vatNumber} onChange={e=>set('vatNumber',e.target.value)}/></label></div></section>
   <section className="dms-panel dms-form-panel"><h2>Contact & address</h2><div className="dms-form-two"><label><span>Address line 1</span><input value={s.address1} onChange={e=>set('address1',e.target.value)}/></label><label><span>Address line 2</span><input value={s.address2} onChange={e=>set('address2',e.target.value)}/></label><label><span>Town / city</span><input value={s.town} onChange={e=>set('town',e.target.value)}/></label><label><span>County</span><input value={s.county} onChange={e=>set('county',e.target.value)}/></label><label><span>Postcode</span><input value={s.postcode} onChange={e=>set('postcode',e.target.value)}/></label><label><span>Telephone</span><input value={s.phone} onChange={e=>set('phone',e.target.value)}/></label><label><span>Email</span><input value={s.email} onChange={e=>set('email',e.target.value)}/></label><label><span>Website</span><input value={s.website} onChange={e=>set('website',e.target.value)}/></label></div></section>
   <section className="dms-panel dms-form-panel"><h2>Document branding</h2><label><span>Dealership logo</span><input type="file" accept="image/*" onChange={logo}/></label>{s.logoData&&<div className="dms-logo-preview"><img src={s.logoData} alt="Business logo preview"/><button onClick={()=>set('logoData','')}>Remove logo</button></div>}<label><span>Document accent colour</span><input type="color" value={s.documentAccent} onChange={e=>set('documentAccent',e.target.value)}/></label><label><span>Invoice footer text</span><textarea rows={4} value={s.footerText} onChange={e=>set('footerText',e.target.value)}/></label></section>
   <section className="dms-panel dms-form-panel"><h2>Bank & invoice details</h2><div className="dms-form-two"><label><span>Bank name</span><input value={s.bankName} onChange={e=>set('bankName',e.target.value)}/></label><label><span>Account name</span><input value={s.accountName} onChange={e=>set('accountName',e.target.value)}/></label><label><span>Sort code</span><input value={s.sortCode} onChange={e=>set('sortCode',e.target.value)}/></label><label><span>Account number</span><input value={s.accountNumber} onChange={e=>set('accountNumber',e.target.value)}/></label></div><label><span>Invoice terms</span><textarea rows={5} value={s.invoiceTerms} onChange={e=>set('invoiceTerms',e.target.value)}/></label></section>
   <section className="dms-panel dms-form-panel" style={{gridColumn:'1 / -1'}}><div className="dms-panel-head"><div><h2>Data Management</h2><span>Cloud connection and legacy browser-data controls</span></div><strong>{cloud==='connected'?'● Cloud Connected':cloud==='checking'?'○ Checking…':'⚠ Cloud Issue'}</strong></div><div className="finance-statement"><div><span>Operational database</span><strong>Supabase Cloud</strong></div><div><span>Connection status</span><strong>{cloudDetail}</strong></div><div><span>Legacy operational browser stores detected</span><strong>{legacyKeys.length}</strong></div></div><div className="finance-warning">Clearing legacy data removes only obsolete browser-stored operational records such as the old DealerCore v1/v2 customers, invoices, workshop, stock and supplier data. It does not delete Supabase cloud records, your sign-in session, business branding, or Finance favourites.</div>{legacyKeys.length?<><div className="finance-ledger-list">{legacyKeys.map(k=><div key={k}><span>{k}</span><strong>Legacy local data</strong></div>)}</div><div style={{display:'flex',gap:10,marginTop:16}}><button className={armed?'dms-primary':'dms-secondary'} onClick={clearLegacy}>{armed?'Confirm clear legacy data':'Clear Legacy Local Data'}</button>{armed&&<button className="dms-secondary" onClick={()=>setArmed(false)}>Cancel</button>}</div></>:<div className="dms-empty">No legacy operational local data detected on this browser.</div>}{cleared.length>0&&<div className="finance-warning">Cleared {cleared.length} legacy browser store{cleared.length===1?'':'s'}. Refresh DealerCore to confirm only cloud operational data remains.</div>}</section>
  </div>
 </DmsShell>
}
