"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Core={customers:any[];equipment:any[];quotes:any[];invoices:any[];payments:any[];workshop:any[];diary:any[];stock:any[];suppliers:any[];cashBuffer:number};
const K="dealercore-v2", OK="dealercore-enterprise-orders", PK="dealercore-enterprise-pos", OPK="dealercore-opportunities-v1";
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(n||0);
const invoiceTotal=(i:any)=>(i.lines||[]).reduce((s:number,l:any)=>s+(+l.qty||0)*(+l.unit||0)*(1+(+l.vat||0)/100),0);

export default function DmsHome(){
 const [core,setCore]=useState<Core>({customers:[],equipment:[],quotes:[],invoices:[],payments:[],workshop:[],diary:[],stock:[],suppliers:[],cashBuffer:0});
 const [orders,setOrders]=useState<any[]>([]),[pos,setPos]=useState<any[]>([]),[opps,setOpps]=useState<any[]>([]),[depot,setDepot]=useState("Princes Risborough");
 useEffect(()=>{try{const c=JSON.parse(localStorage.getItem(K)||"{}");setCore(s=>({...s,...c}));setOrders(JSON.parse(localStorage.getItem(OK)||"[]"));setPos(JSON.parse(localStorage.getItem(PK)||"[]"));setOpps(JSON.parse(localStorage.getItem(OPK)||"[]"))}catch{}},[]);
 const receivables=useMemo(()=>core.invoices.reduce((s,i)=>s+invoiceTotal(i),0)-core.payments.reduce((s,p)=>s+(+p.amount||0),0),[core]);
 const quotePipe=core.quotes.filter(q=>['Draft','Sent'].includes(q.status)).reduce((s,q)=>s+invoiceTotal(q),0);
 const openSales=orders.filter(o=>!['Delivered','Cancelled'].includes(o.status)).reduce((s,o)=>s+(+o.value||0),0);
 const openPo=pos.filter(p=>!['Received','Cancelled'].includes(p.status)).reduce((s,p)=>s+(+p.value||0),0);
 const activeWorkshop=core.workshop.filter(j=>!['Collected'].includes(j.status));
 const lowStock=core.stock.filter(i=>(+i.qty||0)<=1);
 const today=new Date().toISOString().slice(0,10);
 const todayDiary=core.diary.filter(d=>d.date===today&&!d.done);
 const modules=[
  ["Customers","CRM & customer accounts","/enterprise","C"],["Sales","Pipeline, quotes & orders","/enterprise","S"],["Accounts","Invoices, payments & credit","/invoice/new","A"],["Workshop","Jobs, technicians & assets","/enterprise/operations","W"],["Parts","Stock, purchasing & suppliers","/enterprise/operations","P"],["Management","KPIs, exposure & work queues","/enterprise/operations","M"]
 ];
 return <main className="dms-shell"><header className="dms-topbar"><div className="dms-brand"><div className="dms-logo">DC</div><div><strong>DealerCore</strong><span>Dealership Management System</span></div></div><div className="dms-context"><label>Company<select><option>Risborough Group</option></select></label><label>Depot<select value={depot} onChange={e=>setDepot(e.target.value)}><option>Princes Risborough</option><option>All depots</option><option>Demo Depot 2</option></select></label><label>Division<select><option>All divisions</option><option>Garden Machinery</option><option>Golf & Turf</option><option>Garden Care</option></select></label></div><div className="dms-user"><button title="Notifications">●</button><div><b>Jonathan Quinton</b><span>System Administrator</span></div></div></header>
 <aside className="dms-nav"><div className="dms-search"><span>⌕</span><input placeholder="Search customer, serial, order, invoice..."/></div><nav>{modules.map(([name,desc,href,icon])=><Link href={href} key={name}><b>{icon}</b><div><strong>{name}</strong><span>{desc}</span></div></Link>)}</nav><div className="dms-nav-foot"><Link href="/tools">Data & test tools</Link><Link href="/">Legacy operations view</Link></div></aside>
 <section className="dms-content"><div className="dms-pagehead"><div><p>DEALERSHIP COMMAND CENTRE</p><h1>{depot}</h1><span>Operational overview · {new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</span></div><div><button>Refresh</button><Link href="/invoice/new" className="dms-primary">+ New transaction</Link></div></div>
 <div className="dms-kpi-grid"><div><span>Receivables</span><strong>{money(receivables)}</strong><small>{core.invoices.length} invoices</small></div><div><span>Open sales orders</span><strong>{money(openSales)}</strong><small>{orders.filter(o=>!['Delivered','Cancelled'].includes(o.status)).length} live</small></div><div><span>Quote pipeline</span><strong>{money(quotePipe)}</strong><small>{opps.filter(o=>!['Won','Lost'].includes(o.stage)).length} opportunities</small></div><div><span>PO commitments</span><strong>{money(openPo)}</strong><small>{pos.filter(p=>!['Received','Cancelled'].includes(p.status)).length} open POs</small></div><div><span>Workshop WIP</span><strong>{activeWorkshop.length}</strong><small>{activeWorkshop.filter(j=>j.status==='Finished').length} finished</small></div><div><span>Low stock</span><strong>{lowStock.length}</strong><small>{core.stock.length} total lines</small></div></div>
 <div className="dms-workgrid"><section className="dms-panel dms-wide"><div className="dms-panel-head"><div><h2>Operational work queues</h2><span>Items needing attention across the dealership</span></div><button>Configure queues</button></div><div className="dms-queue-table"><div className="dms-queue-head"><span>Area</span><span>Priority</span><span>Work item</span><span>Owner</span><span>Age / due</span><span>Value</span></div>{todayDiary.slice(0,4).map((d:any)=><div className="dms-queue-row" key={d.id}><span>Sales</span><span className="priority amber">Today</span><span><b>{d.title}</b><small>{core.customers.find(c=>c.id===d.customerId)?.name||'General task'}</small></span><span>Sales</span><span>{d.time||'Today'}</span><span>—</span></div>)}{activeWorkshop.filter(j=>j.status==='Finished').slice(0,4).map((j:any)=><div className="dms-queue-row" key={j.id}><span>Workshop</span><span className="priority green">Ready</span><span><b>{j.machine||'Machine ready'}</b><small>{core.customers.find(c=>c.id===j.customerId)?.name||'Customer'}</small></span><span>Workshop</span><span>{j.dueDate||'—'}</span><span>{money((j.labourHours||0)*(j.labourRate||0)+(j.partsSell||0))}</span></div>)}{lowStock.slice(0,4).map((i:any)=><div className="dms-queue-row" key={i.id}><span>Parts</span><span className="priority red">Low</span><span><b>{i.sku||'SKU'} · {i.description}</b><small>Stock quantity {i.qty}</small></span><span>Parts</span><span>Reorder</span><span>{money((i.qty||0)*(i.cost||0))}</span></div>)}{!todayDiary.length&&!activeWorkshop.some(j=>j.status==='Finished')&&!lowStock.length&&<div className="dms-empty">No priority work items in the current dataset.</div>}</div></section>
 <section className="dms-panel"><div className="dms-panel-head"><div><h2>Sales funnel</h2><span>Current opportunity position</span></div><Link href="/enterprise">Open sales</Link></div><div className="dms-funnel">{['Lead','Qualified','Demo / Survey','Quoted','Negotiation','Won'].map(stage=>{const xs=opps.filter(o=>o.stage===stage);const val=xs.reduce((s,o)=>s+(+o.value||0),0);return <div key={stage}><span>{stage}</span><div><i style={{width:`${Math.min(100,Math.max(8,(val/(Math.max(...opps.map(o=>+o.value||0),1)))*100))}%`}}/></div><b>{xs.length}</b><strong>{money(val)}</strong></div>})}</div></section>
 <section className="dms-panel"><div className="dms-panel-head"><div><h2>Workshop status</h2><span>Live WIP by stage</span></div><Link href="/enterprise/operations">Open workshop</Link></div><div className="dms-status-list">{['Booked','Awaiting approval','Awaiting parts','In progress','Finished'].map(s=><div key={s}><span>{s}</span><b>{core.workshop.filter(j=>j.status===s).length}</b></div>)}</div></section>
 <section className="dms-panel dms-wide"><div className="dms-panel-head"><div><h2>Management exposure</h2><span>Commercial values requiring control</span></div><span className="dms-badge">LIVE LOCAL DATA</span></div><div className="dms-exposure"><div><span>Customer receivables</span><strong>{money(receivables)}</strong><small>Cash outstanding</small></div><div><span>Open supplier commitments</span><strong>{money(openPo)}</strong><small>Cash requirement</small></div><div><span>Stock at cost</span><strong>{money(core.stock.reduce((s,i)=>s+(+i.qty||0)*(+i.cost||0),0))}</strong><small>Inventory investment</small></div><div><span>Cash buffer</span><strong>{money(core.cashBuffer||0)}</strong><small>Current configured reserve</small></div></div></section></div>
 </section></main>
}